// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the multi factor auth API operations on <see cref="WorkOSClient"/>.</summary>
    public class MultiFactorAuthService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiFactorAuthService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public MultiFactorAuthService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiFactorAuthService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public MultiFactorAuthService(WorkOSClient client) : base(client) { }

        /// <summary>Verify Challenge</summary>
        /// <remarks>
        /// Verifies an Authentication Challenge.
        /// </remarks>
        /// <param name="id">The unique ID of the Authentication Challenge.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="AuthenticationChallengeVerifyResponse"/> result.</returns>
        public virtual async Task<AuthenticationChallengeVerifyResponse> VerifyChallenge(string id, MultiFactorAuthVerifyChallengeOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<AuthenticationChallengeVerifyResponse>($"/auth/challenges/{id}/verify", options, requestOptions, cancellationToken);
        }

        /// <summary>Enroll Factor</summary>
        /// <remarks>
        /// Enrolls an Authentication Factor to be used as an additional factor of authentication. The returned ID should be used to create an authentication Challenge.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="AuthenticationFactorEnrolled"/> result.</returns>
        public virtual async Task<AuthenticationFactorEnrolled> EnrollFactor(MultiFactorAuthEnrollFactorOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<AuthenticationFactorEnrolled>("/auth/factors/enroll", options, requestOptions, cancellationToken);
        }

        /// <summary>Get Factor</summary>
        /// <remarks>
        /// Gets an Authentication Factor.
        /// </remarks>
        /// <param name="id">The unique ID of the Factor.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="AuthenticationFactor"/> result.</returns>
        public virtual async Task<AuthenticationFactor> GetFactor(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<AuthenticationFactor>($"/auth/factors/{id}", null, requestOptions, cancellationToken);
        }

        /// <summary>Delete Factor</summary>
        /// <remarks>
        /// Permanently deletes an Authentication Factor. It cannot be undone.
        /// </remarks>
        /// <param name="id">The unique ID of the Factor.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task DeleteFactor(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            await this.DeleteAsync($"/auth/factors/{id}", null, requestOptions, cancellationToken);
        }

        /// <summary>Challenge Factor</summary>
        /// <remarks>
        /// Creates a Challenge for an Authentication Factor.
        /// </remarks>
        /// <param name="id">The unique ID of the Authentication Factor to be challenged.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="AuthenticationChallenge"/> result.</returns>
        public virtual async Task<AuthenticationChallenge> ChallengeFactor(string id, MultiFactorAuthChallengeFactorOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<AuthenticationChallenge>($"/auth/factors/{id}/challenge", options, requestOptions, cancellationToken);
        }

        /// <summary>List authentication factors</summary>
        /// <remarks>
        /// Lists the [authentication factors](https://workos.com/docs/reference/authkit/mfa/authentication-factor) for a user.
        /// </remarks>
        /// <param name="userlandUserId">The ID of the [user](https://workos.com/docs/reference/authkit/user).</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="AuthenticationFactor"/> results.</returns>
        public virtual async Task<WorkOSList<AuthenticationFactor>> ListUserAuthFactors(string userlandUserId, MultiFactorAuthListUserAuthFactorsOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<WorkOSList<AuthenticationFactor>>($"/user_management/users/{userlandUserId}/auth_factors", options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="ListUserAuthFactors"/>. Yields individual items across all pages.</summary>
        /// <param name="userlandUserId">The ID of the [user](https://workos.com/docs/reference/authkit/user).</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="AuthenticationFactor"/> items.</returns>
        public virtual IAsyncEnumerable<AuthenticationFactor> ListUserAuthFactorsAutoPagingAsync(string userlandUserId, MultiFactorAuthListUserAuthFactorsOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAutoPagingAsync<AuthenticationFactor>($"/user_management/users/{userlandUserId}/auth_factors", options, requestOptions, cancellationToken);
        }

        /// <summary>Enroll an authentication factor</summary>
        /// <remarks>
        /// Enrolls a user in a new [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor).
        /// </remarks>
        /// <param name="userlandUserId">The ID of the [user](https://workos.com/docs/reference/authkit/user).</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="UserAuthenticationFactorEnrollResponse"/> result.</returns>
        public virtual async Task<UserAuthenticationFactorEnrollResponse> CreateUserAuthFactor(string userlandUserId, MultiFactorAuthCreateUserAuthFactorOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<UserAuthenticationFactorEnrollResponse>($"/user_management/users/{userlandUserId}/auth_factors", options, requestOptions, cancellationToken);
        }
    }
}
