// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the roles API operations on <see cref="WorkOSClient"/>.</summary>
    public class RolesService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RolesService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public RolesService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="RolesService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public RolesService(WorkOSClient client) : base(client) { }

        /// <summary>List roles</summary>
        /// <remarks>
        /// Get a list of all roles for an environment
        /// </remarks>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="RoleListResponse"/> result.</returns>
        public virtual async Task<RoleListResponse> List(RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<RoleListResponse>("/roles", null, requestOptions, cancellationToken);
        }
    }
}
