// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="PipesProviderService.UpdateOrganizationDataIntegrationConfigurationAsync"/>: Configure a provider for an organization</summary>
    public class PipesProviderUpdateOrganizationDataIntegrationConfigurationOptions : BaseOptions
    {
        /// <summary>Whether the provider is enabled for the organization.</summary>
        public bool? Enabled { get; set; }

        /// <summary>The OAuth scopes to request for the organization. Pass `null` to inherit the provider scopes.</summary>
        public List<string>? Scopes { get; set; }

        /// <summary>The OAuth client ID of the organization's own application. Must be provided together with `client_secret`, and only for providers whose credentials are supplied by the organization.</summary>
        public string? ClientId { get; set; }

        /// <summary>The OAuth client secret of the organization's own application. Must be provided together with `client_id`.</summary>
        public string? ClientSecret { get; set; }

        /// <summary>Provider-specific config values to set for the organization, keyed by config field. Only fields the provider declares are accepted, and each value must match that field's pattern. Accepted only for providers whose credentials are organization-managed; for shared or custom credential providers, config belongs on the integration itself (via the data-integrations API) and supplying it here is rejected.</summary>
        public Dictionary<string, string>? Config { get; set; }

    }
}
