// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the platform teams API operations on <see cref="WorkOSClient"/>.</summary>
    public class PlatformTeamsService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlatformTeamsService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public PlatformTeamsService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlatformTeamsService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public PlatformTeamsService(WorkOSClient client) : base(client) { }

        /// <summary>Create a team</summary>
        /// <remarks>
        /// Creates a team along with its default project, a staging environment, and a production environment. An admin invitation is sent to `admin_email`, onboarding is marked complete with AuthKit enabled, and the calling platform is authorized to act inside the team.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="Team"/> result.</returns>
        public virtual async Task<Team> CreateTeamAsync(PlatformTeamsCreateTeamOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<Team>("/platform/teams", options, requestOptions, cancellationToken);
        }

        /// <summary>Compatibility wrapper for <see cref="CreateTeamAsync"/>.</summary>
        public virtual Task<Team> CreateTeam(PlatformTeamsCreateTeamOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.CreateTeamAsync(options, requestOptions, cancellationToken);
        }

        /// <summary>Get a team</summary>
        /// <remarks>
        /// Returns a team, and doubles as a health check on the platform's access to it. Read `production_state` before attempting to create a production environment.
        /// </remarks>
        /// <param name="teamId">The ID of the team.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="Team"/> result.</returns>
        public virtual async Task<Team> GetTeamAsync(string teamId, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<Team>($"/platform/teams/{Uri.EscapeDataString(teamId)}", null, requestOptions, cancellationToken);
        }

        /// <summary>Compatibility wrapper for <see cref="GetTeamAsync"/>.</summary>
        public virtual Task<Team> GetTeam(string teamId, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.GetTeamAsync(teamId, requestOptions, cancellationToken);
        }
    }
}
