// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the admin portal API operations on <see cref="WorkOSClient"/>.</summary>
    public class AdminPortalService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdminPortalService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public AdminPortalService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminPortalService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public AdminPortalService(WorkOSClient client) : base(client) { }

        /// <summary>Generate a Portal Link</summary>
        /// <remarks>
        /// Generate a Portal Link scoped to an Organization.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="PortalLinkResponse"/> result.</returns>
        public virtual async Task<PortalLinkResponse> GenerateLinkAsync(AdminPortalGenerateLinkOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<PortalLinkResponse>("/portal/generate_link", options, requestOptions, cancellationToken);
        }

        /// <summary>Compatibility wrapper for <see cref="GenerateLinkAsync"/>.</summary>
        public virtual Task<PortalLinkResponse> GenerateLink(AdminPortalGenerateLinkOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.GenerateLinkAsync(options, requestOptions, cancellationToken);
        }
    }
}
