// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>
    /// Generated service accessors for WorkOSClient.
    /// </summary>
    public partial class WorkOSClient
    {
        private ApiKeysService apiKeys;

        /// <summary>Gets the <see cref="ApiKeysService"/> for api keys API operations.</summary>
        public virtual ApiKeysService ApiKeys => this.apiKeys ??= new ApiKeysService(this);

        private MultiFactorAuthService multiFactorAuth;

        /// <summary>Gets the <see cref="MultiFactorAuthService"/> for multi factor auth API operations.</summary>
        public virtual MultiFactorAuthService MultiFactorAuth => this.multiFactorAuth ??= new MultiFactorAuthService(this);

        private ConnectService connect;

        /// <summary>Gets the <see cref="ConnectService"/> for connect API operations.</summary>
        public virtual ConnectService Connect => this.connect ??= new ConnectService(this);

        private AuthorizationService authorization;

        /// <summary>Gets the <see cref="AuthorizationService"/> for authorization API operations.</summary>
        public virtual AuthorizationService Authorization => this.authorization ??= new AuthorizationService(this);

        private SSOService sSO;

        /// <summary>Gets the <see cref="SSOService"/> for SSO API operations.</summary>
        public virtual SSOService SSO => this.sSO ??= new SSOService(this);

        private PipesService pipes;

        /// <summary>Gets the <see cref="PipesService"/> for pipes API operations.</summary>
        public virtual PipesService Pipes => this.pipes ??= new PipesService(this);

        private DirectorySyncService directorySync;

        /// <summary>Gets the <see cref="DirectorySyncService"/> for directory sync API operations.</summary>
        public virtual DirectorySyncService DirectorySync => this.directorySync ??= new DirectorySyncService(this);

        private EventsService events;

        /// <summary>Gets the <see cref="EventsService"/> for events API operations.</summary>
        public virtual EventsService Events => this.events ??= new EventsService(this);

        private FeatureFlagsService featureFlags;

        /// <summary>Gets the <see cref="FeatureFlagsService"/> for feature flags API operations.</summary>
        public virtual FeatureFlagsService FeatureFlags => this.featureFlags ??= new FeatureFlagsService(this);

        private OrganizationDomainsService organizationDomains;

        /// <summary>Gets the <see cref="OrganizationDomainsService"/> for organization domains API operations.</summary>
        public virtual OrganizationDomainsService OrganizationDomains => this.organizationDomains ??= new OrganizationDomainsService(this);

        private OrganizationsService organizations;

        /// <summary>Gets the <see cref="OrganizationsService"/> for organizations API operations.</summary>
        public virtual OrganizationsService Organizations => this.organizations ??= new OrganizationsService(this);

        private GroupsService groups;

        /// <summary>Gets the <see cref="GroupsService"/> for groups API operations.</summary>
        public virtual GroupsService Groups => this.groups ??= new GroupsService(this);

        private AdminPortalService adminPortal;

        /// <summary>Gets the <see cref="AdminPortalService"/> for admin portal API operations.</summary>
        public virtual AdminPortalService AdminPortal => this.adminPortal ??= new AdminPortalService(this);

        private RadarService radar;

        /// <summary>Gets the <see cref="RadarService"/> for radar API operations.</summary>
        public virtual RadarService Radar => this.radar ??= new RadarService(this);

        private UserManagementService userManagement;

        /// <summary>Gets the <see cref="UserManagementService"/> for user management API operations.</summary>
        public virtual UserManagementService UserManagement => this.userManagement ??= new UserManagementService(this);

        private UserManagementOrganizationMembershipGroupsService userManagementOrganizationMembershipGroups;

        /// <summary>Gets the <see cref="UserManagementOrganizationMembershipGroupsService"/> for user management organization membership groups API operations.</summary>
        public virtual UserManagementOrganizationMembershipGroupsService UserManagementOrganizationMembershipGroups => this.userManagementOrganizationMembershipGroups ??= new UserManagementOrganizationMembershipGroupsService(this);

        private WebhooksService webhooks;

        /// <summary>Gets the <see cref="WebhooksService"/> for webhooks API operations.</summary>
        public virtual WebhooksService Webhooks => this.webhooks ??= new WebhooksService(this);

        private WidgetsService widgets;

        /// <summary>Gets the <see cref="WidgetsService"/> for widgets API operations.</summary>
        public virtual WidgetsService Widgets => this.widgets ??= new WidgetsService(this);

        private AuditLogsService auditLogs;

        /// <summary>Gets the <see cref="AuditLogsService"/> for audit logs API operations.</summary>
        public virtual AuditLogsService AuditLogs => this.auditLogs ??= new AuditLogsService(this);

    }
}
