// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the events API operations on <see cref="WorkOSClient"/>.</summary>
    public class EventsService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventsService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public EventsService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public EventsService(WorkOSClient client) : base(client) { }

        /// <summary>List events</summary>
        /// <remarks>
        /// List events for the current environment.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="EventSchema"/> results.</returns>
        public virtual async Task<WorkOSList<EventSchema>> ListAsync(EventsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<WorkOSList<EventSchema>>("/events", options, requestOptions, cancellationToken);
        }

        /// <summary>Compatibility wrapper for <see cref="ListAsync"/>.</summary>
        public virtual Task<WorkOSList<EventSchema>> List(EventsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAsync(options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="ListAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="EventSchema"/> items.</returns>
        public virtual IAsyncEnumerable<EventSchema> ListAutoPagingAsync(EventsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAutoPagingAsync<EventSchema>("/events", options, requestOptions, cancellationToken);
        }
    }
}
