// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="DirectorySyncService.ListAsync"/>: List Directories</summary>
    public class DirectorySyncListOptions : ListOptions
    {
        /// <summary>Filter Directories by their associated organization.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>Searchable text to match against Directory names.</summary>
        public string? Search { get; set; }

        /// <summary>Filter Directories by their associated domain.</summary>
        [System.Obsolete("This parameter is deprecated.")]
        public string? Domain { get; set; }

    }

    /// <summary>Request options for <see cref="DirectorySyncService.ListGroupsAsync"/>: List Directory Groups</summary>
    public class DirectorySyncListGroupsOptions : ListOptions
    {
        /// <summary>Unique identifier of the WorkOS Directory. This value can be obtained from the WorkOS dashboard or from the WorkOS API.</summary>
        public string? Directory { get; set; }

        /// <summary>Unique identifier of the WorkOS Directory User. This value can be obtained from the WorkOS API.</summary>
        public string? User { get; set; }

    }

    /// <summary>Request options for <see cref="DirectorySyncService.ListUsersAsync"/>: List Directory Users</summary>
    public class DirectorySyncListUsersOptions : ListOptions
    {
        /// <summary>Unique identifier of the WorkOS Directory. This value can be obtained from the WorkOS dashboard or from the WorkOS API.</summary>
        public string? Directory { get; set; }

        /// <summary>Unique identifier of the WorkOS Directory Group. This value can be obtained from the WorkOS API.</summary>
        public string? Group { get; set; }

    }
}
