// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="UserManagementOrganizationMembershipGroupsService.ListOrganizationMembershipGroupsAsync"/>: List groups</summary>
    public class UserManagementOrganizationMembershipGroupsListOrganizationMembershipGroupsOptions : ListOptions
    {
    }
}
