// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    public class SSOListConnectionsOptions : ListOptions
    {
        /// <summary>Filter Connections by their type.</summary>
        [JsonProperty("connection_type")]
        [STJS.JsonPropertyName("connection_type")]
        public ConnectionsConnectionType? ConnectionType { get; set; }

        /// <summary>Filter Connections by their associated domain.</summary>
        [JsonProperty("domain")]
        [STJS.JsonPropertyName("domain")]
        public string Domain { get; set; }

        /// <summary>Filter Connections by their associated organization.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; }

        /// <summary>Searchable text to match against Connection names.</summary>
        [JsonProperty("search")]
        [STJS.JsonPropertyName("search")]
        public string Search { get; set; }

    }

    public class SSOGetAuthorizationUrlOptions : BaseOptions
    {
        /// <summary>Additional OAuth scopes to request from the identity provider. Only applicable when using OAuth connections.</summary>
        [JsonProperty("provider_scopes")]
        [STJS.JsonPropertyName("provider_scopes")]
        public List<string> ProviderScopes { get; set; }

        /// <summary>Key/value pairs of query parameters to pass to the OAuth provider. Only applicable when using OAuth connections.</summary>
        [JsonProperty("provider_query_params")]
        [STJS.JsonPropertyName("provider_query_params")]
        public Dictionary<string, string> ProviderQueryParams { get; set; }

        /// <summary>Deprecated. Use `connection` or `organization` instead. Used to initiate SSO for a connection by domain. The domain must be associated with a connection in your WorkOS environment.</summary>
        [JsonProperty("domain")]
        [STJS.JsonPropertyName("domain")]
        public string Domain { get; set; }

        /// <summary>Used to initiate OAuth authentication with Google, Microsoft, GitHub, or Apple.</summary>
        [JsonProperty("provider")]
        [STJS.JsonPropertyName("provider")]
        public SSOProvider? Provider { get; set; }

        /// <summary>Where to redirect the user after they complete the authentication process. You must use one of the redirect URIs configured via the [Redirects](https://dashboard.workos.com/redirects) page on the dashboard.</summary>
        [JsonProperty("redirect_uri")]
        [STJS.JsonPropertyName("redirect_uri")]
        public string RedirectUri { get; set; }

        /// <summary>An optional parameter that can be used to encode arbitrary information to help restore application state between redirects. If included, the redirect URI received from WorkOS will contain the exact `state` that was passed.</summary>
        [JsonProperty("state")]
        [STJS.JsonPropertyName("state")]
        public string State { get; set; }

        /// <summary>Used to initiate SSO for a connection. The value should be a WorkOS connection ID.</summary>
        [JsonProperty("connection")]
        [STJS.JsonPropertyName("connection")]
        public string Connection { get; set; }

        /// <summary>Used to initiate SSO for an organization. The value should be a WorkOS organization ID.</summary>
        [JsonProperty("organization")]
        [STJS.JsonPropertyName("organization")]
        public string Organization { get; set; }

        /// <summary>Can be used to pre-fill the domain field when initiating authentication with Microsoft OAuth or with a Google SAML connection type.</summary>
        [JsonProperty("domain_hint")]
        [STJS.JsonPropertyName("domain_hint")]
        public string DomainHint { get; set; }

        /// <summary>Can be used to pre-fill the username/email address field of the IdP sign-in page for the user, if you know their username ahead of time. Currently supported for OAuth, OpenID Connect, Okta, and Entra ID connections.</summary>
        [JsonProperty("login_hint")]
        [STJS.JsonPropertyName("login_hint")]
        public string LoginHint { get; set; }

        /// <summary>A random string generated by the client that is used to mitigate replay attacks.</summary>
        [JsonProperty("nonce")]
        [STJS.JsonPropertyName("nonce")]
        public string Nonce { get; set; }

        [JsonProperty("response_type")]
        [STJS.JsonPropertyName("response_type")]
        internal string ResponseType { get; set; }

        [JsonProperty("client_id")]
        [STJS.JsonPropertyName("client_id")]
        internal string ClientId { get; set; }

    }

    public class SSOGetLogoutUrlOptions : BaseOptions
    {
        /// <summary>The logout token returned from the [Logout Authorize](https://workos.com/docs/reference/sso/logout/authorize) endpoint.</summary>
        [JsonProperty("token")]
        [STJS.JsonPropertyName("token")]
        public string Token { get; set; }

    }

    public class SSOAuthorizeLogoutOptions : BaseOptions
    {
        /// <summary>The unique ID of the profile to log out.</summary>
        [JsonProperty("profile_id")]
        [STJS.JsonPropertyName("profile_id")]
        public string ProfileId { get; set; }

    }

    public class SSOGetProfileAndTokenOptions : BaseOptions
    {
        /// <summary>The authorization code received from the authorization callback.</summary>
        [JsonProperty("code")]
        [STJS.JsonPropertyName("code")]
        public string Code { get; set; }

        [JsonProperty("grant_type")]
        [STJS.JsonPropertyName("grant_type")]
        internal string GrantType { get; set; }

        [JsonProperty("client_id")]
        [STJS.JsonPropertyName("client_id")]
        internal string ClientId { get; set; }

        [JsonProperty("client_secret")]
        [STJS.JsonPropertyName("client_secret")]
        internal string ClientSecret { get; set; }

    }
}
