// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="AuthkitUsersService.ResetPassword"/>: Password reset</summary>
    public class AuthkitUsersResetPasswordOptions : BaseOptions
    {
        /// <summary>The email address of the user to create a password reset token for.</summary>
        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="AuthkitUsersService.ListUsers"/>: List users</summary>
    public class AuthkitUsersListUsersOptions : ListOptions
    {
        [JsonProperty("organization")]
        [STJS.JsonPropertyName("organization")]
        public string? Organization { get; set; }

        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string? OrganizationId { get; set; }

        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string? Email { get; set; }

    }

    /// <summary>Request options for <see cref="AuthkitUsersService.CreateUser"/>: Create a user</summary>
    public class AuthkitUsersCreateUserOptions : BaseOptions
    {
        /// <summary>The email address of the user.</summary>
        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        /// <summary>The password of the user.</summary>
        [JsonProperty("password")]
        [STJS.JsonPropertyName("password")]
        public string? Password { get; set; }

        /// <summary>The hashed password of the user. Requires password_hash_type to be set.</summary>
        [JsonProperty("password_hash")]
        [STJS.JsonPropertyName("password_hash")]
        public string? PasswordHash { get; set; }

        /// <summary>The first name of the user.</summary>
        [JsonProperty("first_name")]
        [STJS.JsonPropertyName("first_name")]
        public string? FirstName { get; set; }

        /// <summary>The last name of the user.</summary>
        [JsonProperty("last_name")]
        [STJS.JsonPropertyName("last_name")]
        public string? LastName { get; set; }

        /// <summary>Whether the user's email has been verified.</summary>
        [JsonProperty("email_verified")]
        [STJS.JsonPropertyName("email_verified")]
        public bool? EmailVerified { get; set; }

        /// <summary>The external ID of the user.</summary>
        [JsonProperty("external_id")]
        [STJS.JsonPropertyName("external_id")]
        public string? ExternalId { get; set; }

        [JsonProperty("password_hash_type")]
        [STJS.JsonPropertyName("password_hash_type")]
        public CreateUserPasswordHashType? PasswordHashType { get; set; }

        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public Dictionary<string, object>? Metadata { get; set; }

    }

    /// <summary>Request options for <see cref="AuthkitUsersService.UpdateUser"/>: Update a user</summary>
    public class AuthkitUsersUpdateUserOptions : BaseOptions
    {
        /// <summary>The email address of the user.</summary>
        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string? Email { get; set; }

        /// <summary>The first name of the user.</summary>
        [JsonProperty("first_name")]
        [STJS.JsonPropertyName("first_name")]
        public string? FirstName { get; set; }

        /// <summary>The last name of the user.</summary>
        [JsonProperty("last_name")]
        [STJS.JsonPropertyName("last_name")]
        public string? LastName { get; set; }

        /// <summary>Whether the user's email has been verified.</summary>
        [JsonProperty("email_verified")]
        [STJS.JsonPropertyName("email_verified")]
        public bool? EmailVerified { get; set; }

        /// <summary>The password of the user.</summary>
        [JsonProperty("password")]
        [STJS.JsonPropertyName("password")]
        public string? Password { get; set; }

        /// <summary>The hashed password of the user. Requires password_hash_type to be set.</summary>
        [JsonProperty("password_hash")]
        [STJS.JsonPropertyName("password_hash")]
        public string? PasswordHash { get; set; }

        /// <summary>The external ID of the user.</summary>
        [JsonProperty("external_id")]
        [STJS.JsonPropertyName("external_id")]
        public string? ExternalId { get; set; }

        /// <summary>The user's preferred locale.</summary>
        [JsonProperty("locale")]
        [STJS.JsonPropertyName("locale")]
        public string? Locale { get; set; }

        [JsonProperty("password_hash_type")]
        [STJS.JsonPropertyName("password_hash_type")]
        public CreateUserPasswordHashType? PasswordHashType { get; set; }

        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public Dictionary<string, object>? Metadata { get; set; }

    }

    /// <summary>Request options for <see cref="AuthkitUsersService.ListUserAuthorizedApplications"/>: List authorized applications</summary>
    public class AuthkitUsersListUserAuthorizedApplicationsOptions : ListOptions
    {
    }
}
