// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Handles Widgets operations.</summary>
    public class WidgetsService : Service
    {
        public WidgetsService() { }

        public WidgetsService(WorkOSClient client) : base(client) { }

        /// <summary>Generate a widget token</summary>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="WidgetSessionTokenResponse"/> result.</returns>
        public async Task<WidgetSessionTokenResponse> CreateToken(WidgetsCreateTokenOptions options, RequestOptions requestOptions = null, CancellationToken cancellationToken = default)
        {
            var request = new WorkOSRequest
            {
                Method = HttpMethod.Post,
                Path = "/widgets/token",
                Options = options,
                RequestOptions = requestOptions,
            };
            return await this.Client.MakeAPIRequest<WidgetSessionTokenResponse>(request, cancellationToken);
        }
    }
}
