// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents audit log configuration log stream type values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum AuditLogConfigurationLogStreamType
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "AzureSentinel")]
        AzureSentinel,
        [EnumMember(Value = "Datadog")]
        Datadog,
        [EnumMember(Value = "GenericHttps")]
        GenericHttps,
        [EnumMember(Value = "GoogleCloudStorage")]
        GoogleCloudStorage,
        [EnumMember(Value = "S3")]
        S3,
        [EnumMember(Value = "Splunk")]
        Splunk,
    }
}
