// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents audit log configuration state values.</summary>
    [JsonConverter(typeof(StringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum AuditLogConfigurationState
    {
        [EnumMember(Value = "active")]
        Active,
        [EnumMember(Value = "inactive")]
        Inactive,
        [EnumMember(Value = "disabled")]
        Disabled,
    }
}
