// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents connection deactivated data connection type values.</summary>
    [JsonConverter(typeof(StringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum ConnectionDeactivatedDataConnectionType
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "ADFSSAML")]
        Adfssaml,
        [EnumMember(Value = "AdpOidc")]
        AdpOidc,
        [EnumMember(Value = "AppleOAuth")]
        AppleOAuth,
        [EnumMember(Value = "Auth0Migration")]
        Auth0Migration,
        [EnumMember(Value = "Auth0SAML")]
        Auth0SAML,
        [EnumMember(Value = "AzureSAML")]
        AzureSAML,
        [EnumMember(Value = "BitbucketOAuth")]
        BitbucketOAuth,
        [EnumMember(Value = "CasSAML")]
        CasSAML,
        [EnumMember(Value = "ClassLinkSAML")]
        ClassLinkSAML,
        [EnumMember(Value = "CleverOIDC")]
        CleverOidc,
        [EnumMember(Value = "CloudflareSAML")]
        CloudflareSAML,
        [EnumMember(Value = "CyberArkSAML")]
        CyberArkSAML,
        [EnumMember(Value = "DiscordOAuth")]
        DiscordOAuth,
        [EnumMember(Value = "DuoSAML")]
        DuoSAML,
        [EnumMember(Value = "EntraIdOIDC")]
        EntraIdOidc,
        [EnumMember(Value = "GenericOIDC")]
        GenericOidc,
        [EnumMember(Value = "GenericSAML")]
        GenericSAML,
        [EnumMember(Value = "GitHubOAuth")]
        GitHubOAuth,
        [EnumMember(Value = "GitLabOAuth")]
        GitLabOAuth,
        [EnumMember(Value = "GoogleOAuth")]
        GoogleOAuth,
        [EnumMember(Value = "GoogleOIDC")]
        GoogleOidc,
        [EnumMember(Value = "GoogleSAML")]
        GoogleSAML,
        [EnumMember(Value = "IntuitOAuth")]
        IntuitOAuth,
        [EnumMember(Value = "JumpCloudSAML")]
        JumpCloudSAML,
        [EnumMember(Value = "KeycloakSAML")]
        KeycloakSAML,
        [EnumMember(Value = "LastPassSAML")]
        LastPassSAML,
        [EnumMember(Value = "LinkedInOAuth")]
        LinkedInOAuth,
        [EnumMember(Value = "LoginGovOidc")]
        LoginGovOidc,
        [EnumMember(Value = "MagicLink")]
        MagicLink,
        [EnumMember(Value = "MicrosoftOAuth")]
        MicrosoftOAuth,
        [EnumMember(Value = "MiniOrangeSAML")]
        MiniOrangeSAML,
        [EnumMember(Value = "NetIqSAML")]
        NetIqSAML,
        [EnumMember(Value = "OktaOIDC")]
        OktaOidc,
        [EnumMember(Value = "OktaSAML")]
        OktaSAML,
        [EnumMember(Value = "OneLoginSAML")]
        OneLoginSAML,
        [EnumMember(Value = "OracleSAML")]
        OracleSAML,
        [EnumMember(Value = "PingFederateSAML")]
        PingFederateSAML,
        [EnumMember(Value = "PingOneSAML")]
        PingOneSAML,
        [EnumMember(Value = "RipplingSAML")]
        RipplingSAML,
        [EnumMember(Value = "SalesforceSAML")]
        SalesforceSAML,
        [EnumMember(Value = "ShibbolethGenericSAML")]
        ShibbolethGenericSAML,
        [EnumMember(Value = "ShibbolethSAML")]
        ShibbolethSAML,
        [EnumMember(Value = "SimpleSamlPhpSAML")]
        SimpleSAMLPhpSAML,
        [EnumMember(Value = "SalesforceOAuth")]
        SalesforceOAuth,
        [EnumMember(Value = "SlackOAuth")]
        SlackOAuth,
        [EnumMember(Value = "TestIdp")]
        TestIdp,
        [EnumMember(Value = "VercelMarketplaceOAuth")]
        VercelMarketplaceOAuth,
        [EnumMember(Value = "VercelOAuth")]
        VercelOAuth,
        [EnumMember(Value = "VMwareSAML")]
        VMwareSAML,
        [EnumMember(Value = "XeroOAuth")]
        XeroOAuth,
    }
}
