// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents connection status values.</summary>
    [JsonConverter(typeof(StringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum ConnectionStatus
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "linked")]
        Linked,
        [EnumMember(Value = "unlinked")]
        Unlinked,
    }
}
