// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create connection oidc options token authentication method values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum CreateConnectionOidcOptionsTokenAuthenticationMethod
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "client_secret_post")]
        ClientSecretPost,
        [EnumMember(Value = "client_secret_basic")]
        ClientSecretBasic,
        [EnumMember(Value = "private_key_jwt")]
        PrivateKeyJWT,
    }
}
