// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents dsync user updated data state values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum DsyncUserUpdatedDataState
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "active")]
        Active,
        [EnumMember(Value = "suspended")]
        Suspended,
        [EnumMember(Value = "inactive")]
        Inactive,
    }
}
