// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents flag deleted context actor source values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum FlagDeletedContextActorSource
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "api")]
        Api,
        [EnumMember(Value = "dashboard")]
        Dashboard,
        [EnumMember(Value = "system")]
        System,
    }
}
