// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents organization domain verification failed data organization domain state values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum OrganizationDomainVerificationFailedDataOrganizationDomainState
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "failed")]
        Failed,
        [EnumMember(Value = "legacy_verified")]
        LegacyVerified,
        [EnumMember(Value = "pending")]
        Pending,
        [EnumMember(Value = "unverified")]
        Unverified,
        [EnumMember(Value = "verified")]
        Verified,
    }
}
