// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents organization domain verification failed data reason values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum OrganizationDomainVerificationFailedDataReason
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "domain_verification_period_expired")]
        DomainVerificationPeriodExpired,
        [EnumMember(Value = "domain_verified_by_other_organization")]
        DomainVerifiedByOtherOrganization,
    }
}
