// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents radar standalone response control values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum RadarStandaloneResponseControl
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "bot_detection")]
        BotDetection,
        [EnumMember(Value = "brute_force_attack")]
        BruteForceAttack,
        [EnumMember(Value = "credential_stuffing")]
        CredentialStuffing,
        [EnumMember(Value = "domain_sign_up_rate_limit")]
        DomainSignUpRateLimit,
        [EnumMember(Value = "ip_sign_up_rate_limit")]
        IpSignUpRateLimit,
        [EnumMember(Value = "impossible_travel")]
        ImpossibleTravel,
        [EnumMember(Value = "repeat_sign_up")]
        RepeatSignUp,
        [EnumMember(Value = "stale_account")]
        StaleAccount,
        [EnumMember(Value = "unrecognized_device")]
        UnrecognizedDevice,
        [EnumMember(Value = "restriction")]
        Restriction,
    }
}
