// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents radar standalone assess request action values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum RadarStandaloneAssessRequestAction
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "sign-up")]
        SignUp,
        [EnumMember(Value = "sign-in")]
        SignIn,
    }
}
