// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents resource export completed data resource type values.</summary>
    [JsonConverter(typeof(WorkOSNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum ResourceExportCompletedDataResourceType
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "users")]
        Users,
        [EnumMember(Value = "organizations")]
        Organizations,
        [EnumMember(Value = "events")]
        Events,
        [EnumMember(Value = "sessions")]
        Sessions,
        [EnumMember(Value = "auditLogEvents")]
        AuditLogEvents,
    }
}
