// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents vault metadata read data actor source values.</summary>
    [JsonConverter(typeof(StringEnumConverter))]
    [STJS.JsonConverter(typeof(WorkOSStringEnumConverterFactory))]
    public enum VaultMetadataReadDataActorSource
    {
        [EnumMember(Value = "api")]
        Api,
        [EnumMember(Value = "dashboard")]
        Dashboard,
    }
}
