// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="AuthorizationService.Check"/>: Check authorization</summary>
    public class AuthorizationCheckOptions : BaseOptions
    {
        /// <summary>The slug of the permission to check.</summary>
        public string PermissionSlug { get; set; } = default!;

        /// <summary>The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`.</summary>
        public string? ResourceId { get; set; }

        /// <summary>The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`.</summary>
        public string? ResourceExternalId { get; set; }

        /// <summary>The slug of the resource type. Required with `resource_external_id`. Mutually exclusive with `resource_id`.</summary>
        public string? ResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.ListOrganizationMembershipResources"/>: List resources for organization membership</summary>
    public class AuthorizationListOrganizationMembershipResourcesOptions : ListOptions
    {
        /// <summary>The permission slug to filter by. Only child resources where the organization membership has this permission are returned.</summary>
        public string PermissionSlug { get; set; } = default!;

        [JsonIgnore]
        [STJS.JsonIgnore]
        public ParentResource ParentResource { get; set; } = default!;

    }

    public abstract class ParentResource { }

    public class ParentResourceById : ParentResource
    {
        public string ParentResourceId { get; set; } = default!;

    }

    public class ParentResourceByExternalId : ParentResource
    {
        public string ParentResourceTypeSlug { get; set; } = default!;

        public string ParentResourceExternalId { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="AuthorizationService.ListResourcePermissions"/>: List effective permissions for an organization membership on a resource</summary>
    public class AuthorizationListResourcePermissionsOptions : ListOptions
    {
    }

    /// <summary>Request options for <see cref="AuthorizationService.ListEffectivePermissionsByExternalId"/>: List effective permissions for an organization membership on a resource by external ID</summary>
    public class AuthorizationListEffectivePermissionsByExternalIdOptions : ListOptions
    {
    }

    /// <summary>Request options for <see cref="AuthorizationService.ListOrganizationMembershipRoleAssignments"/>: List role assignments</summary>
    public class AuthorizationListOrganizationMembershipRoleAssignmentsOptions : ListOptions
    {
    }

    /// <summary>Request options for <see cref="AuthorizationService.AssignRole"/>: Assign a role</summary>
    public class AuthorizationAssignRoleOptions : BaseOptions
    {
        /// <summary>The slug of the role to assign.</summary>
        public string RoleSlug { get; set; } = default!;

        /// <summary>The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`.</summary>
        public string? ResourceId { get; set; }

        /// <summary>The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`.</summary>
        public string? ResourceExternalId { get; set; }

        /// <summary>The resource type slug. Required with `resource_external_id`. Mutually exclusive with `resource_id`.</summary>
        public string? ResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.RemoveRole"/>: Remove a role assignment</summary>
    public class AuthorizationRemoveRoleOptions : BaseOptions
    {
        /// <summary>The slug of the role to remove.</summary>
        public string RoleSlug { get; set; } = default!;

        /// <summary>The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`.</summary>
        public string? ResourceId { get; set; }

        /// <summary>The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`.</summary>
        public string? ResourceExternalId { get; set; }

        /// <summary>The resource type slug. Required with `resource_external_id`. Mutually exclusive with `resource_id`.</summary>
        public string? ResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.CreateOrganizationRole"/>: Create a custom role</summary>
    public class AuthorizationCreateOrganizationRoleOptions : BaseOptions
    {
        /// <summary>A unique identifier for the role within the organization. When provided, must begin with 'org-' and contain only lowercase letters, numbers, hyphens, and underscores. When omitted, a slug is auto-generated from the role name and a random suffix.</summary>
        public string? Slug { get; set; }

        /// <summary>A descriptive name for the role.</summary>
        public string Name { get; set; } = default!;

        /// <summary>An optional description of the role's purpose.</summary>
        public string? Description { get; set; }

        /// <summary>The slug of the resource type the role is scoped to.</summary>
        public string? ResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.UpdateOrganizationRole"/>: Update a custom role</summary>
    public class AuthorizationUpdateOrganizationRoleOptions : BaseOptions
    {
        /// <summary>A descriptive name for the role.</summary>
        public string? Name { get; set; }

        /// <summary>An optional description of the role's purpose.</summary>
        public string? Description { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.CreateRolePermission"/>: Add a permission to a custom role</summary>
    public class AuthorizationCreateRolePermissionOptions : BaseOptions
    {
        /// <summary>The slug of the permission to add to the role.</summary>
        public string Slug { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="AuthorizationService.UpdateRolePermissions"/>: Set permissions for a custom role</summary>
    public class AuthorizationUpdateRolePermissionsOptions : BaseOptions
    {
        /// <summary>The permission slugs to assign to the role.</summary>
        public List<string> Permissions { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="AuthorizationService.UpdateOrganizationResource"/>: Update a resource by external ID</summary>
    public class AuthorizationUpdateOrganizationResourceOptions : BaseOptions
    {
        /// <summary>A display name for the resource.</summary>
        public string? Name { get; set; }

        /// <summary>An optional description of the resource.</summary>
        public string? Description { get; set; }

        /// <summary>The ID of the parent resource. Mutually exclusive with `parent_resource_external_id` and `parent_resource_type_slug`.</summary>
        public string? ParentResourceId { get; set; }

        /// <summary>The external ID of the parent resource. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`.</summary>
        public string? ParentResourceExternalId { get; set; }

        /// <summary>The resource type slug of the parent resource. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`.</summary>
        public string? ParentResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.DeleteOrganizationResource"/>: Delete an authorization resource by external ID</summary>
    public class AuthorizationDeleteOrganizationResourceOptions : BaseOptions
    {
        /// <summary>If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.</summary>
        public bool? CascadeDelete { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.ListResourceOrganizationMemberships"/>: List memberships for a resource by external ID</summary>
    public class AuthorizationListResourceOrganizationMembershipsOptions : ListOptions
    {
        /// <summary>The permission slug to filter by. Only users with this permission on the resource are returned.</summary>
        public string PermissionSlug { get; set; } = default!;

        /// <summary>Filter by assignment type. Use "direct" for direct assignments only, or "indirect" to include inherited assignments.</summary>
        public AuthorizationAssignment? Assignment { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.ListResources"/>: List resources</summary>
    public class AuthorizationListResourcesOptions : ListOptions
    {
        /// <summary>Filter resources by organization ID.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>Filter resources by resource type slug.</summary>
        public string? ResourceTypeSlug { get; set; }

        /// <summary>Filter resources by parent resource ID.</summary>
        public string? ParentResourceId { get; set; }

        /// <summary>Filter resources by parent resource type slug.</summary>
        public string? ParentResourceTypeSlug { get; set; }

        /// <summary>Filter resources by parent external ID.</summary>
        public string? ParentExternalId { get; set; }

        /// <summary>Search resources by name.</summary>
        public string? Search { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.CreateResource"/>: Create an authorization resource</summary>
    public class AuthorizationCreateResourceOptions : BaseOptions
    {
        /// <summary>An external identifier for the resource.</summary>
        public string ExternalId { get; set; } = default!;

        /// <summary>A display name for the resource.</summary>
        public string Name { get; set; } = default!;

        /// <summary>An optional description of the resource.</summary>
        public string? Description { get; set; }

        /// <summary>The slug of the resource type.</summary>
        public string ResourceTypeSlug { get; set; } = default!;

        /// <summary>The ID of the organization this resource belongs to.</summary>
        public string OrganizationId { get; set; } = default!;

        /// <summary>The ID of the parent resource. Mutually exclusive with `parent_resource_external_id` and `parent_resource_type_slug`.</summary>
        public string? ParentResourceId { get; set; }

        /// <summary>The external ID of the parent resource. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`.</summary>
        public string? ParentResourceExternalId { get; set; }

        /// <summary>The resource type slug of the parent resource. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`.</summary>
        public string? ParentResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.UpdateResource"/>: Update a resource</summary>
    public class AuthorizationUpdateResourceOptions : BaseOptions
    {
        /// <summary>A display name for the resource.</summary>
        public string? Name { get; set; }

        /// <summary>An optional description of the resource.</summary>
        public string? Description { get; set; }

        /// <summary>The ID of the parent resource. Mutually exclusive with `parent_resource_external_id` and `parent_resource_type_slug`.</summary>
        public string? ParentResourceId { get; set; }

        /// <summary>The external ID of the parent resource. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`.</summary>
        public string? ParentResourceExternalId { get; set; }

        /// <summary>The resource type slug of the parent resource. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`.</summary>
        public string? ParentResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.DeleteResource"/>: Delete an authorization resource</summary>
    public class AuthorizationDeleteResourceOptions : BaseOptions
    {
        /// <summary>If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.</summary>
        public bool? CascadeDelete { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.ListMembershipsForResource"/>: List organization memberships for resource</summary>
    public class AuthorizationListMembershipsForResourceOptions : ListOptions
    {
        /// <summary>The permission slug to filter by. Only users with this permission on the resource are returned.</summary>
        public string PermissionSlug { get; set; } = default!;

        /// <summary>Filter by assignment type. Use `direct` for direct assignments only, or `indirect` to include inherited assignments.</summary>
        public AuthorizationAssignment? Assignment { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.CreateEnvironmentRole"/>: Create an environment role</summary>
    public class AuthorizationCreateEnvironmentRoleOptions : BaseOptions
    {
        /// <summary>A unique slug for the role.</summary>
        public string Slug { get; set; } = default!;

        /// <summary>A descriptive name for the role.</summary>
        public string Name { get; set; } = default!;

        /// <summary>An optional description of the role.</summary>
        public string? Description { get; set; }

        /// <summary>The slug of the resource type the role is scoped to.</summary>
        public string? ResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.UpdateEnvironmentRole"/>: Update an environment role</summary>
    public class AuthorizationUpdateEnvironmentRoleOptions : BaseOptions
    {
        /// <summary>A descriptive name for the role.</summary>
        public string? Name { get; set; }

        /// <summary>An optional description of the role.</summary>
        public string? Description { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.AddEnvironmentRolePermission"/>: Add a permission to an environment role</summary>
    public class AuthorizationAddEnvironmentRolePermissionOptions : BaseOptions
    {
        /// <summary>The slug of the permission to add to the role.</summary>
        public string Slug { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="AuthorizationService.SetEnvironmentRolePermissions"/>: Set permissions for an environment role</summary>
    public class AuthorizationSetEnvironmentRolePermissionsOptions : BaseOptions
    {
        /// <summary>The permission slugs to assign to the role.</summary>
        public List<string> Permissions { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="AuthorizationService.ListPermissions"/>: List permissions</summary>
    public class AuthorizationListPermissionsOptions : ListOptions
    {
    }

    /// <summary>Request options for <see cref="AuthorizationService.CreatePermission"/>: Create a permission</summary>
    public class AuthorizationCreatePermissionOptions : BaseOptions
    {
        /// <summary>A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.</summary>
        public string Slug { get; set; } = default!;

        /// <summary>A descriptive name for the Permission.</summary>
        public string Name { get; set; } = default!;

        /// <summary>An optional description of the Permission.</summary>
        public string? Description { get; set; }

        /// <summary>The slug of the resource type this permission is scoped to.</summary>
        public string? ResourceTypeSlug { get; set; }

    }

    /// <summary>Request options for <see cref="AuthorizationService.UpdatePermission"/>: Update a permission</summary>
    public class AuthorizationUpdatePermissionOptions : BaseOptions
    {
        /// <summary>A descriptive name for the Permission.</summary>
        public string? Name { get; set; }

        /// <summary>An optional description of the Permission.</summary>
        public string? Description { get; set; }

    }
}
