// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Handles OrganizationDomains operations.</summary>
    public class OrganizationDomainsService : Service
    {
        public OrganizationDomainsService() { }

        public OrganizationDomainsService(WorkOSClient client) : base(client) { }

        /// <summary>Create an Organization Domain</summary>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="OrganizationDomain"/> result.</returns>
        public virtual async Task<OrganizationDomain> Create(OrganizationDomainsCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var request = new WorkOSRequest
            {
                Method = HttpMethod.Post,
                Path = "/organization_domains",
                Options = options,
                RequestOptions = requestOptions,
            };
            return await this.Client.MakeAPIRequest<OrganizationDomain>(request, cancellationToken);
        }

        /// <summary>Get an Organization Domain</summary>
        /// <param name="id">Unique identifier of the organization domain.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="OrganizationDomainStandAlone"/> result.</returns>
        public virtual async Task<OrganizationDomainStandAlone> Get(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var request = new WorkOSRequest
            {
                Method = HttpMethod.Get,
                Path = $"/organization_domains/{id}",
                RequestOptions = requestOptions,
            };
            return await this.Client.MakeAPIRequest<OrganizationDomainStandAlone>(request, cancellationToken);
        }

        /// <summary>Delete an Organization Domain</summary>
        /// <param name="id">Unique identifier of the organization domain.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task Delete(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var request = new WorkOSRequest
            {
                Method = HttpMethod.Delete,
                Path = $"/organization_domains/{id}",
                RequestOptions = requestOptions,
            };
            await this.Client.MakeRawAPIRequest(request, cancellationToken);
        }

        /// <summary>Verify an Organization Domain</summary>
        /// <param name="id">Unique identifier of the organization domain.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="OrganizationDomainStandAlone"/> result.</returns>
        public virtual async Task<OrganizationDomainStandAlone> Verify(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var request = new WorkOSRequest
            {
                Method = HttpMethod.Post,
                Path = $"/organization_domains/{id}/verify",
                RequestOptions = requestOptions,
            };
            return await this.Client.MakeAPIRequest<OrganizationDomainStandAlone>(request, cancellationToken);
        }
    }
}
