// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the authkit organization membership API operations on <see cref="WorkOSClient"/>.</summary>
    public class AuthkitOrganizationMembershipService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthkitOrganizationMembershipService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public AuthkitOrganizationMembershipService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthkitOrganizationMembershipService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public AuthkitOrganizationMembershipService(WorkOSClient client) : base(client) { }

        /// <summary>List organization memberships</summary>
        /// <remarks>
        /// Get a list of all organization memberships matching the criteria specified.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="string"/> results.</returns>
        public virtual async Task<WorkOSList<string>> ListOrganizationMemberships(AuthkitOrganizationMembershipListOrganizationMembershipsOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<WorkOSList<string>>("/user_management/organization_memberships", options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="ListOrganizationMemberships"/>. Yields individual items across all pages.</summary>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="string"/> items.</returns>
        public virtual IAsyncEnumerable<string> ListOrganizationMembershipsAutoPagingAsync(AuthkitOrganizationMembershipListOrganizationMembershipsOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAutoPagingAsync<string>("/user_management/organization_memberships", options, requestOptions, cancellationToken);
        }

        /// <summary>Create an organization membership</summary>
        /// <remarks>
        /// Creates a new organization membership for the given organization and user.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="UserOrganizationMembershipsCreateResponse"/> result.</returns>
        public virtual async Task<UserOrganizationMembershipsCreateResponse> CreateOrganizationMembership(AuthkitOrganizationMembershipCreateOrganizationMembershipOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<UserOrganizationMembershipsCreateResponse>("/user_management/organization_memberships", options, requestOptions, cancellationToken);
        }

        /// <summary>Get an organization membership</summary>
        /// <remarks>
        /// Get the details of an existing organization membership.
        /// </remarks>
        /// <param name="id">The id.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="UserOrganizationMembershipsGetResponse"/> result.</returns>
        public virtual async Task<UserOrganizationMembershipsGetResponse> GetOrganizationMembership(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<UserOrganizationMembershipsGetResponse>($"/user_management/organization_memberships/{id}", null, requestOptions, cancellationToken);
        }

        /// <summary>Updates an organization membership</summary>
        /// <remarks>
        /// Updates a existing organization membership with the given id.
        /// </remarks>
        /// <param name="id">The id.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="UserOrganizationMembershipsUpdateResponse"/> result.</returns>
        public virtual async Task<UserOrganizationMembershipsUpdateResponse> UpdateOrganizationMembership(string id, AuthkitOrganizationMembershipUpdateOrganizationMembershipOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PutAsync<UserOrganizationMembershipsUpdateResponse>($"/user_management/organization_memberships/{id}", options, requestOptions, cancellationToken);
        }

        /// <summary>Delete an organization membership</summary>
        /// <remarks>
        /// Deletes an existing organization membership.
        /// </remarks>
        /// <param name="id">The id.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task DeleteOrganizationMembership(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            await this.DeleteAsync($"/user_management/organization_memberships/{id}", null, requestOptions, cancellationToken);
        }

        /// <summary>Deactivates an organization membership</summary>
        /// <remarks>
        /// Deactivates an organization membership.
        /// </remarks>
        /// <param name="id">The id.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="UserOrganizationMembershipsDeactivateResponse"/> result.</returns>
        public virtual async Task<UserOrganizationMembershipsDeactivateResponse> DeactivateOrganizationMembership(string id, AuthkitOrganizationMembershipDeactivateOrganizationMembershipOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PutAsync<UserOrganizationMembershipsDeactivateResponse>($"/user_management/organization_memberships/{id}/deactivate", options, requestOptions, cancellationToken);
        }

        /// <summary>Reactivates an organization membership</summary>
        /// <remarks>
        /// Reactivates an organization membership.
        /// </remarks>
        /// <param name="id">The id.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="UserOrganizationMembershipsReactivateResponse"/> result.</returns>
        public virtual async Task<UserOrganizationMembershipsReactivateResponse> ReactivateOrganizationMembership(string id, AuthkitOrganizationMembershipReactivateOrganizationMembershipOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PutAsync<UserOrganizationMembershipsReactivateResponse>($"/user_management/organization_memberships/{id}/reactivate", options, requestOptions, cancellationToken);
        }
    }
}
