// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.IO;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class ApiKeysServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly ApiKeysService service;

        public ApiKeysServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new ApiKeysService(client);
        }

        [Fact]
        public async Task TestCreateValidations()
        {
            var fixture = File.ReadAllText("testdata/api_key_validation_response.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/api_keys/validations", HttpStatusCode.OK, fixture);
            var result = await this.service.CreateValidations(new ApiKeysCreateValidationsOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/api_keys/validations");
        }

        [Fact]
        public async Task TestDelete()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/api_keys/test_id", HttpStatusCode.NoContent, "");
            await this.service.Delete("test_id");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/api_keys/test_id");
        }

        [Fact]
        public async Task TestListOrganizationApiKeys()
        {
            var fixture = File.ReadAllText("testdata/list_api_key.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/organizations/test_organizationId/api_keys", HttpStatusCode.OK, fixture);
            var result = await this.service.ListOrganizationApiKeys("test_organizationId", new ApiKeysListOrganizationApiKeysOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/organizations/test_organizationId/api_keys");
        }

        [Fact]
        public async Task TestCreateOrganizationApiKeys()
        {
            var fixture = File.ReadAllText("testdata/api_key_with_value.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/organizations/test_organizationId/api_keys", HttpStatusCode.OK, fixture);
            var result = await this.service.CreateOrganizationApiKeys("test_organizationId", new ApiKeysCreateOrganizationApiKeysOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Id);
            Assert.NotEmpty(result.Name);
            Assert.NotEmpty(result.ObfuscatedValue);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/organizations/test_organizationId/api_keys");
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationError>(() => this.service.CreateValidations(new ApiKeysCreateValidationsOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundError>(() => this.service.CreateValidations(new ApiKeysCreateValidationsOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityError>(() => this.service.CreateValidations(new ApiKeysCreateValidationsOptions()));
        }
    }
}
