// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class AuthorizationServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly AuthorizationService service;

        public AuthorizationServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                ClientId = "client_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new AuthorizationService(client);
        }

        [Fact]
        public async Task TestCheck()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_check.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/organization_memberships/test_organization_membership_id/check", HttpStatusCode.OK, fixture);
            var options = new AuthorizationCheckOptions();
            options.PermissionSlug = "test_permission_slug";
            var result = await this.service.Check("test_organization_membership_id", options);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/organization_memberships/test_organization_membership_id/check");
            await this.httpMock.AssertRequestBodyContainsAsync("permission_slug", "test_permission_slug");
        }

        [Fact]
        public async Task TestListOrganizationMembershipResources()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_authorization_resource.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources", HttpStatusCode.OK, fixture);
            var result = await this.service.ListOrganizationMembershipResources("test_organization_membership_id", new AuthorizationListOrganizationMembershipResourcesOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources");
        }

        [Fact]
        public async Task TestListOrganizationMembershipResourcesEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListOrganizationMembershipResources("test_organization_membership_id", new AuthorizationListOrganizationMembershipResourcesOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestListResourcePermissions()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_authorization_permission.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_id/permissions", HttpStatusCode.OK, fixture);
            var result = await this.service.ListResourcePermissions("test_organization_membership_id", "test_resource_id", new AuthorizationListResourcePermissionsOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_id/permissions");
        }

        [Fact]
        public async Task TestListResourcePermissionsEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_id/permissions", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListResourcePermissions("test_organization_membership_id", "test_resource_id", new AuthorizationListResourcePermissionsOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestListEffectivePermissionsByExternalId()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_authorization_permission.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_type_slug/test_external_id/permissions", HttpStatusCode.OK, fixture);
            var result = await this.service.ListEffectivePermissionsByExternalId("test_organization_membership_id", "test_resource_type_slug", "test_external_id", new AuthorizationListEffectivePermissionsByExternalIdOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_type_slug/test_external_id/permissions");
        }

        [Fact]
        public async Task TestListEffectivePermissionsByExternalIdEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_type_slug/test_external_id/permissions", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListEffectivePermissionsByExternalId("test_organization_membership_id", "test_resource_type_slug", "test_external_id", new AuthorizationListEffectivePermissionsByExternalIdOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestListOrganizationMembershipRoleAssignments()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_role_assignment.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", HttpStatusCode.OK, fixture);
            var result = await this.service.ListOrganizationMembershipRoleAssignments("test_organization_membership_id", new AuthorizationListOrganizationMembershipRoleAssignmentsOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/role_assignments");
        }

        [Fact]
        public async Task TestListOrganizationMembershipRoleAssignmentsEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListOrganizationMembershipRoleAssignments("test_organization_membership_id", new AuthorizationListOrganizationMembershipRoleAssignmentsOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestAssignRole()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role_assignment.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", HttpStatusCode.OK, fixture);
            var options = new AuthorizationAssignRoleOptions();
            options.RoleSlug = "test_role_slug";
            var result = await this.service.AssignRole("test_organization_membership_id", options);
            Assert.NotNull(result);
            Assert.Equal("role_assignment_01HXYZ123456789ABCDEFGH", result.Id);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/organization_memberships/test_organization_membership_id/role_assignments");
            await this.httpMock.AssertRequestBodyContainsAsync("role_slug", "test_role_slug");
        }

        [Fact]
        public async Task TestRemoveRole()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", HttpStatusCode.NoContent, "");
            await this.service.RemoveRole("test_organization_membership_id", new AuthorizationRemoveRoleOptions());
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/authorization/organization_memberships/test_organization_membership_id/role_assignments");
        }

        [Fact]
        public async Task TestDeleteOrganizationMembershipRoleAssignment()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/authorization/organization_memberships/test_organization_membership_id/role_assignments/test_role_assignment_id", HttpStatusCode.NoContent, "");
            await this.service.DeleteOrganizationMembershipRoleAssignment("test_organization_membership_id", "test_role_assignment_id");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/authorization/organization_memberships/test_organization_membership_id/role_assignments/test_role_assignment_id");
        }

        [Fact]
        public async Task TestListOrganizationRoles()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role_list.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organizations/test_organizationId/roles", HttpStatusCode.OK, fixture);
            var result = await this.service.ListOrganizationRoles("test_organizationId");
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organizations/test_organizationId/roles");
        }

        [Fact]
        public async Task TestCreateOrganizationRole()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/organizations/test_organizationId/roles", HttpStatusCode.OK, fixture);
            var options = new AuthorizationCreateOrganizationRoleOptions();
            options.Name = "test_name";
            var result = await this.service.CreateOrganizationRole("test_organizationId", options);
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/organizations/test_organizationId/roles");
            await this.httpMock.AssertRequestBodyContainsAsync("name", "test_name");
        }

        [Fact]
        public async Task TestGetOrganizationRole()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organizations/test_organizationId/roles/test_slug", HttpStatusCode.OK, fixture);
            var result = await this.service.GetOrganizationRole("test_organizationId", "test_slug");
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organizations/test_organizationId/roles/test_slug");
        }

        [Fact]
        public async Task TestUpdateOrganizationRole()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/authorization/organizations/test_organizationId/roles/test_slug", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateOrganizationRole("test_organizationId", "test_slug", new AuthorizationUpdateOrganizationRoleOptions());
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/authorization/organizations/test_organizationId/roles/test_slug");
        }

        [Fact]
        public async Task TestDeleteOrganizationRole()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/authorization/organizations/test_organizationId/roles/test_slug", HttpStatusCode.NoContent, "");
            await this.service.DeleteOrganizationRole("test_organizationId", "test_slug");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/authorization/organizations/test_organizationId/roles/test_slug");
        }

        [Fact]
        public async Task TestCreateRolePermission()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/organizations/test_organizationId/roles/test_slug/permissions", HttpStatusCode.OK, fixture);
            var options = new AuthorizationCreateRolePermissionOptions();
            options.Slug = "test_slug";
            var result = await this.service.CreateRolePermission("test_organizationId", "test_slug", options);
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/organizations/test_organizationId/roles/test_slug/permissions");
            await this.httpMock.AssertRequestBodyContainsAsync("slug", "test_slug");
        }

        [Fact]
        public async Task TestUpdateRolePermissions()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Put, "/authorization/organizations/test_organizationId/roles/test_slug/permissions", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateRolePermissions("test_organizationId", "test_slug", new AuthorizationUpdateRolePermissionsOptions());
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Put, "/authorization/organizations/test_organizationId/roles/test_slug/permissions");
        }

        [Fact]
        public async Task TestDeleteRolePermission()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/authorization/organizations/test_organizationId/roles/test_slug/permissions/test_permissionSlug", HttpStatusCode.NoContent, "");
            await this.service.DeleteRolePermission("test_organizationId", "test_slug", "test_permissionSlug");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/authorization/organizations/test_organizationId/roles/test_slug/permissions/test_permissionSlug");
        }

        [Fact]
        public async Task TestGetOrganizationResource()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_resource.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id", HttpStatusCode.OK, fixture);
            var result = await this.service.GetOrganizationResource("test_organization_id", "test_resource_type_slug", "test_external_id");
            Assert.NotNull(result);
            Assert.Equal("authz_resource_01HXYZ123456789ABCDEFGH", result.Id);
            Assert.Equal("Website Redesign", result.Name);
            Assert.Equal("org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id");
        }

        [Fact]
        public async Task TestUpdateOrganizationResource()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_resource.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateOrganizationResource("test_organization_id", "test_resource_type_slug", "test_external_id", new AuthorizationUpdateOrganizationResourceOptions());
            Assert.NotNull(result);
            Assert.Equal("authz_resource_01HXYZ123456789ABCDEFGH", result.Id);
            Assert.Equal("Website Redesign", result.Name);
            Assert.Equal("org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id");
        }

        [Fact]
        public async Task TestDeleteOrganizationResource()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id", HttpStatusCode.NoContent, "");
            await this.service.DeleteOrganizationResource("test_organization_id", "test_resource_type_slug", "test_external_id", new AuthorizationDeleteOrganizationResourceOptions());
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id");
        }

        [Fact]
        public async Task TestListResourceOrganizationMemberships()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_user_organization_membership_base_list_data.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id/organization_memberships", HttpStatusCode.OK, fixture);
            var result = await this.service.ListResourceOrganizationMemberships("test_organization_id", "test_resource_type_slug", "test_external_id", new AuthorizationListResourceOrganizationMembershipsOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id/organization_memberships");
        }

        [Fact]
        public async Task TestListResourceOrganizationMembershipsEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id/organization_memberships", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListResourceOrganizationMemberships("test_organization_id", "test_resource_type_slug", "test_external_id", new AuthorizationListResourceOrganizationMembershipsOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestListResources()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_authorization_resource.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/resources", HttpStatusCode.OK, fixture);
            var result = await this.service.ListResources(new AuthorizationListResourcesOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/resources");
        }

        [Fact]
        public async Task TestListResourcesEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/resources", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListResources(new AuthorizationListResourcesOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestCreateResource()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_resource.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/resources", HttpStatusCode.OK, fixture);
            var options = new AuthorizationCreateResourceOptions();
            options.ExternalId = "test_external_id";
            options.Name = "test_name";
            var result = await this.service.CreateResource(options);
            Assert.NotNull(result);
            Assert.Equal("authz_resource_01HXYZ123456789ABCDEFGH", result.Id);
            Assert.Equal("Website Redesign", result.Name);
            Assert.Equal("org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/resources");
            await this.httpMock.AssertRequestBodyContainsAsync("external_id", "test_external_id");
            await this.httpMock.AssertRequestBodyContainsAsync("name", "test_name");
        }

        [Fact]
        public async Task TestGetResource()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_resource.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/resources/test_resource_id", HttpStatusCode.OK, fixture);
            var result = await this.service.GetResource("test_resource_id");
            Assert.NotNull(result);
            Assert.Equal("authz_resource_01HXYZ123456789ABCDEFGH", result.Id);
            Assert.Equal("Website Redesign", result.Name);
            Assert.Equal("org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/resources/test_resource_id");
        }

        [Fact]
        public async Task TestUpdateResource()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_resource.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/authorization/resources/test_resource_id", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateResource("test_resource_id", new AuthorizationUpdateResourceOptions());
            Assert.NotNull(result);
            Assert.Equal("authz_resource_01HXYZ123456789ABCDEFGH", result.Id);
            Assert.Equal("Website Redesign", result.Name);
            Assert.Equal("org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/authorization/resources/test_resource_id");
        }

        [Fact]
        public async Task TestDeleteResource()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/authorization/resources/test_resource_id", HttpStatusCode.NoContent, "");
            await this.service.DeleteResource("test_resource_id", new AuthorizationDeleteResourceOptions());
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/authorization/resources/test_resource_id");
        }

        [Fact]
        public async Task TestListMembershipsForResource()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_user_organization_membership_base_list_data.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/resources/test_resource_id/organization_memberships", HttpStatusCode.OK, fixture);
            var result = await this.service.ListMembershipsForResource("test_resource_id", new AuthorizationListMembershipsForResourceOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/resources/test_resource_id/organization_memberships");
        }

        [Fact]
        public async Task TestListMembershipsForResourceEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/resources/test_resource_id/organization_memberships", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListMembershipsForResource("test_resource_id", new AuthorizationListMembershipsForResourceOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestListEnvironmentRoles()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role_list.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/roles", HttpStatusCode.OK, fixture);
            var result = await this.service.ListEnvironmentRoles();
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/roles");
        }

        [Fact]
        public async Task TestCreateEnvironmentRole()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/roles", HttpStatusCode.OK, fixture);
            var options = new AuthorizationCreateEnvironmentRoleOptions();
            options.Slug = "test_slug";
            options.Name = "test_name";
            var result = await this.service.CreateEnvironmentRole(options);
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/roles");
            await this.httpMock.AssertRequestBodyContainsAsync("slug", "test_slug");
            await this.httpMock.AssertRequestBodyContainsAsync("name", "test_name");
        }

        [Fact]
        public async Task TestGetEnvironmentRole()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/roles/test_slug", HttpStatusCode.OK, fixture);
            var result = await this.service.GetEnvironmentRole("test_slug");
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/roles/test_slug");
        }

        [Fact]
        public async Task TestUpdateEnvironmentRole()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/authorization/roles/test_slug", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateEnvironmentRole("test_slug", new AuthorizationUpdateEnvironmentRoleOptions());
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/authorization/roles/test_slug");
        }

        [Fact]
        public async Task TestAddEnvironmentRolePermission()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/roles/test_slug/permissions", HttpStatusCode.OK, fixture);
            var options = new AuthorizationAddEnvironmentRolePermissionOptions();
            options.Slug = "test_slug";
            var result = await this.service.AddEnvironmentRolePermission("test_slug", options);
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/roles/test_slug/permissions");
            await this.httpMock.AssertRequestBodyContainsAsync("slug", "test_slug");
        }

        [Fact]
        public async Task TestSetEnvironmentRolePermissions()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role.json");
            this.httpMock.MockResponse(HttpMethod.Put, "/authorization/roles/test_slug/permissions", HttpStatusCode.OK, fixture);
            var result = await this.service.SetEnvironmentRolePermissions("test_slug", new AuthorizationSetEnvironmentRolePermissionsOptions());
            Assert.NotNull(result);
            Assert.Equal("role_01EHQMYV6MBK39QC5PZXHY59C3", result.Id);
            Assert.Equal("admin", result.Slug);
            Assert.Equal("Admin", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Put, "/authorization/roles/test_slug/permissions");
        }

        [Fact]
        public async Task TestListPermissions()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_authorization_permission.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/permissions", HttpStatusCode.OK, fixture);
            var result = await this.service.ListPermissions(new AuthorizationListPermissionsOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/permissions");
        }

        [Fact]
        public async Task TestListPermissionsEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/permissions", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListPermissions(new AuthorizationListPermissionsOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestCreatePermission()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_permission.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/authorization/permissions", HttpStatusCode.OK, fixture);
            var options = new AuthorizationCreatePermissionOptions();
            options.Slug = "test_slug";
            options.Name = "test_name";
            var result = await this.service.CreatePermission(options);
            Assert.NotNull(result);
            Assert.Equal("perm_01HXYZ123456789ABCDEFGHIJ", result.Id);
            Assert.Equal("documents:read", result.Slug);
            Assert.Equal("View Documents", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/authorization/permissions");
            await this.httpMock.AssertRequestBodyContainsAsync("slug", "test_slug");
            await this.httpMock.AssertRequestBodyContainsAsync("name", "test_name");
        }

        [Fact]
        public async Task TestGetPermission()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_permission.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/authorization/permissions/test_slug", HttpStatusCode.OK, fixture);
            var result = await this.service.GetPermission("test_slug");
            Assert.NotNull(result);
            Assert.Equal("perm_01HXYZ123456789ABCDEFGHIJ", result.Id);
            Assert.Equal("documents:read", result.Slug);
            Assert.Equal("View Documents", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/authorization/permissions/test_slug");
        }

        [Fact]
        public async Task TestUpdatePermission()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_permission.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/authorization/permissions/test_slug", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdatePermission("test_slug", new AuthorizationUpdatePermissionOptions());
            Assert.NotNull(result);
            Assert.Equal("perm_01HXYZ123456789ABCDEFGHIJ", result.Id);
            Assert.Equal("documents:read", result.Slug);
            Assert.Equal("View Documents", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/authorization/permissions/test_slug");
        }

        [Fact]
        public async Task TestDeletePermission()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/authorization/permissions/test_slug", HttpStatusCode.NoContent, "");
            await this.service.DeletePermission("test_slug");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/authorization/permissions/test_slug");
        }

        [Fact]
        public async Task TestListOrganizationMembershipResourcesAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_resource.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<AuthorizationResource>();
            await foreach (var item in this.service.ListOrganizationMembershipResourcesAutoPagingAsync("test_organization_membership_id", new AuthorizationListOrganizationMembershipResourcesOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListOrganizationMembershipResourcesAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources", HttpStatusCode.OK, new[] { empty });

            var items = new List<AuthorizationResource>();
            await foreach (var item in this.service.ListOrganizationMembershipResourcesAutoPagingAsync("test_organization_membership_id", new AuthorizationListOrganizationMembershipResourcesOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListResourcePermissionsAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_permission.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_id/permissions", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<AuthorizationPermission>();
            await foreach (var item in this.service.ListResourcePermissionsAutoPagingAsync("test_organization_membership_id", "test_resource_id", new AuthorizationListResourcePermissionsOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListResourcePermissionsAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_id/permissions", HttpStatusCode.OK, new[] { empty });

            var items = new List<AuthorizationPermission>();
            await foreach (var item in this.service.ListResourcePermissionsAutoPagingAsync("test_organization_membership_id", "test_resource_id", new AuthorizationListResourcePermissionsOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListEffectivePermissionsByExternalIdAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_permission.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_type_slug/test_external_id/permissions", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<AuthorizationPermission>();
            await foreach (var item in this.service.ListEffectivePermissionsByExternalIdAutoPagingAsync("test_organization_membership_id", "test_resource_type_slug", "test_external_id", new AuthorizationListEffectivePermissionsByExternalIdOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListEffectivePermissionsByExternalIdAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/resources/test_resource_type_slug/test_external_id/permissions", HttpStatusCode.OK, new[] { empty });

            var items = new List<AuthorizationPermission>();
            await foreach (var item in this.service.ListEffectivePermissionsByExternalIdAutoPagingAsync("test_organization_membership_id", "test_resource_type_slug", "test_external_id", new AuthorizationListEffectivePermissionsByExternalIdOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListOrganizationMembershipRoleAssignmentsAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/role_assignment.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<RoleAssignment>();
            await foreach (var item in this.service.ListOrganizationMembershipRoleAssignmentsAutoPagingAsync("test_organization_membership_id", new AuthorizationListOrganizationMembershipRoleAssignmentsOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListOrganizationMembershipRoleAssignmentsAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organization_memberships/test_organization_membership_id/role_assignments", HttpStatusCode.OK, new[] { empty });

            var items = new List<RoleAssignment>();
            await foreach (var item in this.service.ListOrganizationMembershipRoleAssignmentsAutoPagingAsync("test_organization_membership_id", new AuthorizationListOrganizationMembershipRoleAssignmentsOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListResourceOrganizationMembershipsAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/user_organization_membership_base_list_data.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id/organization_memberships", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<UserOrganizationMembershipBaseListData>();
            await foreach (var item in this.service.ListResourceOrganizationMembershipsAutoPagingAsync("test_organization_id", "test_resource_type_slug", "test_external_id", new AuthorizationListResourceOrganizationMembershipsOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListResourceOrganizationMembershipsAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/organizations/test_organization_id/resources/test_resource_type_slug/test_external_id/organization_memberships", HttpStatusCode.OK, new[] { empty });

            var items = new List<UserOrganizationMembershipBaseListData>();
            await foreach (var item in this.service.ListResourceOrganizationMembershipsAutoPagingAsync("test_organization_id", "test_resource_type_slug", "test_external_id", new AuthorizationListResourceOrganizationMembershipsOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListResourcesAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_resource.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/resources", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<AuthorizationResource>();
            await foreach (var item in this.service.ListResourcesAutoPagingAsync(new AuthorizationListResourcesOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListResourcesAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/resources", HttpStatusCode.OK, new[] { empty });

            var items = new List<AuthorizationResource>();
            await foreach (var item in this.service.ListResourcesAutoPagingAsync(new AuthorizationListResourcesOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListMembershipsForResourceAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/user_organization_membership_base_list_data.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/resources/test_resource_id/organization_memberships", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<UserOrganizationMembershipBaseListData>();
            await foreach (var item in this.service.ListMembershipsForResourceAutoPagingAsync("test_resource_id", new AuthorizationListMembershipsForResourceOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListMembershipsForResourceAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/resources/test_resource_id/organization_memberships", HttpStatusCode.OK, new[] { empty });

            var items = new List<UserOrganizationMembershipBaseListData>();
            await foreach (var item in this.service.ListMembershipsForResourceAutoPagingAsync("test_resource_id", new AuthorizationListMembershipsForResourceOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListPermissionsAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/authorization_permission.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/permissions", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<AuthorizationPermission>();
            await foreach (var item in this.service.ListPermissionsAutoPagingAsync(new AuthorizationListPermissionsOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListPermissionsAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/authorization/permissions", HttpStatusCode.OK, new[] { empty });

            var items = new List<AuthorizationPermission>();
            await foreach (var item in this.service.ListPermissionsAutoPagingAsync(new AuthorizationListPermissionsOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.Check("test_organization_membership_id", new AuthorizationCheckOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.Check("test_organization_membership_id", new AuthorizationCheckOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.Check("test_organization_membership_id", new AuthorizationCheckOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.Check("test_organization_membership_id", new AuthorizationCheckOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.Check("test_organization_membership_id", new AuthorizationCheckOptions()));
        }
    }
}
