// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class DirectorySyncServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly DirectorySyncService service;

        public DirectorySyncServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                ClientId = "client_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new DirectorySyncService(client);
        }

        [Fact]
        public async Task TestList()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_directory.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/directories", HttpStatusCode.OK, fixture);
            var result = await this.service.List(new DirectorySyncListOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/directories");
        }

        [Fact]
        public async Task TestListEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/directories", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.List(new DirectorySyncListOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestGet()
        {
            var fixture = System.IO.File.ReadAllText("testdata/directory.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/directories/test_id", HttpStatusCode.OK, fixture);
            var result = await this.service.Get("test_id");
            Assert.NotNull(result);
            Assert.Equal("directory_01ECAZ4NV9QMV47GW873HDCX74", result.Id);
            Assert.Equal("org_01EHZNVPK3SFK441A1RGBFSHRT", result.OrganizationId);
            Assert.Equal("sPa12dwRQ", result.ExternalKey);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/directories/test_id");
        }

        [Fact]
        public async Task TestDelete()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/directories/test_id", HttpStatusCode.NoContent, "");
            await this.service.Delete("test_id");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/directories/test_id");
        }

        [Fact]
        public async Task TestListGroups()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_directory_group.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/directory_groups", HttpStatusCode.OK, fixture);
            var result = await this.service.ListGroups(new DirectorySyncListGroupsOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/directory_groups");
        }

        [Fact]
        public async Task TestListGroupsEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/directory_groups", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListGroups(new DirectorySyncListGroupsOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestGetGroup()
        {
            var fixture = System.IO.File.ReadAllText("testdata/directory_group.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/directory_groups/test_id", HttpStatusCode.OK, fixture);
            var result = await this.service.GetGroup("test_id");
            Assert.NotNull(result);
            Assert.Equal("directory_group_01E1JJS84MFPPQ3G655FHTKX6Z", result.Id);
            Assert.Equal("02grqrue4294w24", result.IdpId);
            Assert.Equal("directory_01ECAZ4NV9QMV47GW873HDCX74", result.DirectoryId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/directory_groups/test_id");
        }

        [Fact]
        public async Task TestListUsers()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_directory_user_with_groups.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/directory_users", HttpStatusCode.OK, fixture);
            var result = await this.service.ListUsers(new DirectorySyncListUsersOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/directory_users");
        }

        [Fact]
        public async Task TestListUsersEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/directory_users", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListUsers(new DirectorySyncListUsersOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestGetUser()
        {
            var fixture = System.IO.File.ReadAllText("testdata/directory_user_with_groups.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/directory_users/test_id", HttpStatusCode.OK, fixture);
            var result = await this.service.GetUser("test_id");
            Assert.NotNull(result);
            Assert.Equal("directory_user_01E1JG7J09H96KYP8HM9B0G5SJ", result.Id);
            Assert.Equal("directory_01ECAZ4NV9QMV47GW873HDCX74", result.DirectoryId);
            Assert.Equal("org_01EZTR6WYX1A0DSE2CYMGXQ24Y", result.OrganizationId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/directory_users/test_id");
        }

        [Fact]
        public async Task TestListAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/directory.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/directories", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<Directory>();
            await foreach (var item in this.service.ListAutoPagingAsync(new DirectorySyncListOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/directories", HttpStatusCode.OK, new[] { empty });

            var items = new List<Directory>();
            await foreach (var item in this.service.ListAutoPagingAsync(new DirectorySyncListOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListGroupsAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/directory_group.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/directory_groups", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<DirectoryGroup>();
            await foreach (var item in this.service.ListGroupsAutoPagingAsync(new DirectorySyncListGroupsOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListGroupsAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/directory_groups", HttpStatusCode.OK, new[] { empty });

            var items = new List<DirectoryGroup>();
            await foreach (var item in this.service.ListGroupsAutoPagingAsync(new DirectorySyncListGroupsOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListUsersAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/directory_user_with_groups.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/directory_users", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<DirectoryUserWithGroups>();
            await foreach (var item in this.service.ListUsersAutoPagingAsync(new DirectorySyncListUsersOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListUsersAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/directory_users", HttpStatusCode.OK, new[] { empty });

            var items = new List<DirectoryUserWithGroups>();
            await foreach (var item in this.service.ListUsersAutoPagingAsync(new DirectorySyncListUsersOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.List(new DirectorySyncListOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.List(new DirectorySyncListOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.List(new DirectorySyncListOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.List(new DirectorySyncListOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.List(new DirectorySyncListOptions()));
        }
    }
}
