// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.IO;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class EventsServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly EventsService service;

        public EventsServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new EventsService(client);
        }

        [Fact]
        public async Task TestList()
        {
            var fixture = File.ReadAllText("testdata/list_event_schema.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/events", HttpStatusCode.OK, fixture);
            var result = await this.service.List(new EventsListOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/events");
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationError>(() => this.service.List(new EventsListOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundError>(() => this.service.List(new EventsListOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityError>(() => this.service.List(new EventsListOptions()));
        }
    }
}
