// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class GroupsServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly GroupsService service;

        public GroupsServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                ClientId = "client_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new GroupsService(client);
        }

        [Fact]
        public async Task TestListOrganizationGroupsAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_group.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/organizations/test_organizationId/groups", HttpStatusCode.OK, fixture);
            var result = await this.service.ListOrganizationGroupsAsync("test_organizationId", new GroupsListOrganizationGroupsOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/organizations/test_organizationId/groups");
        }

        [Fact]
        public async Task TestListOrganizationGroupsAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/organizations/test_organizationId/groups", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListOrganizationGroupsAsync("test_organizationId", new GroupsListOrganizationGroupsOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestCreateOrganizationGroupAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/group.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/organizations/test_organizationId/groups", HttpStatusCode.OK, fixture);
            var options = new GroupsCreateOrganizationGroupOptions();
            options.Name = "test_name";
            var result = await this.service.CreateOrganizationGroupAsync("test_organizationId", options);
            Assert.NotNull(result);
            Assert.Equal("group_01HXYZ123456789ABCDEFGHIJ", result.Id);
            Assert.Equal("org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationId);
            Assert.Equal("Engineering", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/organizations/test_organizationId/groups");
            await this.httpMock.AssertRequestBodyContainsAsync("name", "test_name");
        }

        [Fact]
        public async Task TestGetOrganizationGroupAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/group.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/organizations/test_organizationId/groups/test_groupId", HttpStatusCode.OK, fixture);
            var result = await this.service.GetOrganizationGroupAsync("test_organizationId", "test_groupId");
            Assert.NotNull(result);
            Assert.Equal("group_01HXYZ123456789ABCDEFGHIJ", result.Id);
            Assert.Equal("org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationId);
            Assert.Equal("Engineering", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/organizations/test_organizationId/groups/test_groupId");
        }

        [Fact]
        public async Task TestUpdateOrganizationGroupAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/group.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/organizations/test_organizationId/groups/test_groupId", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateOrganizationGroupAsync("test_organizationId", "test_groupId", new GroupsUpdateOrganizationGroupOptions());
            Assert.NotNull(result);
            Assert.Equal("group_01HXYZ123456789ABCDEFGHIJ", result.Id);
            Assert.Equal("org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationId);
            Assert.Equal("Engineering", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/organizations/test_organizationId/groups/test_groupId");
        }

        [Fact]
        public async Task TestDeleteOrganizationGroupAsync()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/organizations/test_organizationId/groups/test_groupId", HttpStatusCode.NoContent, "");
            await this.service.DeleteOrganizationGroupAsync("test_organizationId", "test_groupId");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/organizations/test_organizationId/groups/test_groupId");
        }

        [Fact]
        public async Task TestListOrganizationMembershipsAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_user_organization_membership_base_list_data.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/organizations/test_organizationId/groups/test_groupId/organization-memberships", HttpStatusCode.OK, fixture);
            var result = await this.service.ListOrganizationMembershipsAsync("test_organizationId", "test_groupId", new GroupsListOrganizationMembershipsOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/organizations/test_organizationId/groups/test_groupId/organization-memberships");
        }

        [Fact]
        public async Task TestListOrganizationMembershipsAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/organizations/test_organizationId/groups/test_groupId/organization-memberships", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListOrganizationMembershipsAsync("test_organizationId", "test_groupId", new GroupsListOrganizationMembershipsOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestCreateOrganizationMembershipAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/group.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/organizations/test_organizationId/groups/test_groupId/organization-memberships", HttpStatusCode.OK, fixture);
            var options = new GroupsCreateOrganizationMembershipOptions();
            options.OrganizationMembershipId = "test_organization_membership_id";
            var result = await this.service.CreateOrganizationMembershipAsync("test_organizationId", "test_groupId", options);
            Assert.NotNull(result);
            Assert.Equal("group_01HXYZ123456789ABCDEFGHIJ", result.Id);
            Assert.Equal("org_01EHWNCE74X7JSDV0X3SZ3KJNY", result.OrganizationId);
            Assert.Equal("Engineering", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/organizations/test_organizationId/groups/test_groupId/organization-memberships");
            await this.httpMock.AssertRequestBodyContainsAsync("organization_membership_id", "test_organization_membership_id");
        }

        [Fact]
        public async Task TestDeleteOrganizationMembershipAsync()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/organizations/test_organizationId/groups/test_groupId/organization-memberships/test_omId", HttpStatusCode.NoContent, "");
            await this.service.DeleteOrganizationMembershipAsync("test_organizationId", "test_groupId", "test_omId");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/organizations/test_organizationId/groups/test_groupId/organization-memberships/test_omId");
        }

        [Fact]
        public async Task TestListOrganizationGroupsAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/group.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/organizations/test_organizationId/groups", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<Group>();
            await foreach (var item in this.service.ListOrganizationGroupsAutoPagingAsync("test_organizationId", new GroupsListOrganizationGroupsOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListOrganizationGroupsAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/organizations/test_organizationId/groups", HttpStatusCode.OK, new[] { empty });

            var items = new List<Group>();
            await foreach (var item in this.service.ListOrganizationGroupsAutoPagingAsync("test_organizationId", new GroupsListOrganizationGroupsOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestListOrganizationMembershipsAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/user_organization_membership_base_list_data.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/organizations/test_organizationId/groups/test_groupId/organization-memberships", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<UserOrganizationMembershipBaseListData>();
            await foreach (var item in this.service.ListOrganizationMembershipsAutoPagingAsync("test_organizationId", "test_groupId", new GroupsListOrganizationMembershipsOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListOrganizationMembershipsAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/organizations/test_organizationId/groups/test_groupId/organization-memberships", HttpStatusCode.OK, new[] { empty });

            var items = new List<UserOrganizationMembershipBaseListData>();
            await foreach (var item in this.service.ListOrganizationMembershipsAutoPagingAsync("test_organizationId", "test_groupId", new GroupsListOrganizationMembershipsOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.ListOrganizationGroupsAsync("test_organizationId", new GroupsListOrganizationGroupsOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.ListOrganizationGroupsAsync("test_organizationId", new GroupsListOrganizationGroupsOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.ListOrganizationGroupsAsync("test_organizationId", new GroupsListOrganizationGroupsOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.ListOrganizationGroupsAsync("test_organizationId", new GroupsListOrganizationGroupsOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.ListOrganizationGroupsAsync("test_organizationId", new GroupsListOrganizationGroupsOptions()));
        }
    }
}
