// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class PipesPipeServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly PipesPipeService service;

        public PipesPipeServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                ClientId = "client_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new PipesPipeService(client);
        }

        [Fact]
        public async Task TestAuthorizeDataIntegration()
        {
            var fixture = System.IO.File.ReadAllText("testdata/data_integrations_get_data_integration_authorize_url_response.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/data-integrations/test_slug/authorize", HttpStatusCode.OK, fixture);
            var options = new PipesPipeAuthorizeDataIntegrationOptions();
            options.UserId = "test_user_id";
            var result = await this.service.AuthorizeDataIntegration("test_slug", options);
            Assert.NotNull(result);
            Assert.Equal("https://example.com/authorize", result.Url);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/data-integrations/test_slug/authorize");
            await this.httpMock.AssertRequestBodyContainsAsync("user_id", "test_user_id");
        }

        [Fact]
        public async Task TestCreateDataIntegrationToken()
        {
            var fixture = System.IO.File.ReadAllText("testdata/data_integrations_get_user_token_response.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/data-integrations/test_slug/token", HttpStatusCode.OK, fixture);
            var options = new PipesPipeCreateDataIntegrationTokenOptions();
            options.UserId = "test_user_id";
            var result = await this.service.CreateDataIntegrationToken("test_slug", options);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/data-integrations/test_slug/token");
            await this.httpMock.AssertRequestBodyContainsAsync("user_id", "test_user_id");
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationError>(() => this.service.AuthorizeDataIntegration("test_slug", new PipesPipeAuthorizeDataIntegrationOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundError>(() => this.service.AuthorizeDataIntegration("test_slug", new PipesPipeAuthorizeDataIntegrationOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityError>(() => this.service.AuthorizeDataIntegration("test_slug", new PipesPipeAuthorizeDataIntegrationOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededError>(() => this.service.AuthorizeDataIntegration("test_slug", new PipesPipeAuthorizeDataIntegrationOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerError>(() => this.service.AuthorizeDataIntegration("test_slug", new PipesPipeAuthorizeDataIntegrationOptions()));
        }
    }
}
