// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class VaultServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly VaultService service;

        public VaultServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                ClientId = "client_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new VaultService(client);
        }

        [Fact]
        public async Task TestCreateDataKeyAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/create_data_key_response.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/vault/v1/keys/data-key", HttpStatusCode.OK, fixture);
            var result = await this.service.CreateDataKeyAsync(new VaultCreateDataKeyOptions());
            Assert.NotNull(result);
            Assert.Equal("bf51ccec-78b4-5200-b383-35730e71ef61", result.Id);
            Assert.Equal("DR9idtey9MpMrA1VRFrz30HB1yNgL2PoHZyjAkFeWgg=", result.DataKey);
            Assert.Equal("V09TLkVLTS52MQBiZjUxY2NlYy03OGI0LTUyMDAtYjM4My0zNTczMGU3MWVmNjEBATEBJGJmNjVlMzI2LTQzYTAtNGIyMC04OGM0LTA3ZmYzZGU1NDM0YwF0YmY2NWUzMjYtNDNhMC00YjIwLTg4YzQtMDdmZjNkZTU0MzRj", result.EncryptedKeys);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/vault/v1/keys/data-key");
        }

        [Fact]
        public async Task TestCreateDecryptAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/decrypt_response.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/vault/v1/keys/decrypt", HttpStatusCode.OK, fixture);
            var options = new VaultCreateDecryptOptions();
            options.Keys = "test_keys";
            var result = await this.service.CreateDecryptAsync(options);
            Assert.NotNull(result);
            Assert.Equal("bf51ccec-78b4-5200-b383-35730e71ef61", result.Id);
            Assert.Equal("DR9idtey9MpMrA1VRFrz30HB1yNgL2PoHZyjAkFeWgg=", result.DataKey);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/vault/v1/keys/decrypt");
            await this.httpMock.AssertRequestBodyContainsAsync("keys", "test_keys");
        }

        [Fact]
        public async Task TestCreateRekeyAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/create_data_key_response.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/vault/v1/keys/rekey", HttpStatusCode.OK, fixture);
            var options = new VaultCreateRekeyOptions();
            options.EncryptedKeys = "test_encrypted_keys";
            var result = await this.service.CreateRekeyAsync(options);
            Assert.NotNull(result);
            Assert.Equal("bf51ccec-78b4-5200-b383-35730e71ef61", result.Id);
            Assert.Equal("DR9idtey9MpMrA1VRFrz30HB1yNgL2PoHZyjAkFeWgg=", result.DataKey);
            Assert.Equal("V09TLkVLTS52MQBiZjUxY2NlYy03OGI0LTUyMDAtYjM4My0zNTczMGU3MWVmNjEBATEBJGJmNjVlMzI2LTQzYTAtNGIyMC04OGM0LTA3ZmYzZGU1NDM0YwF0YmY2NWUzMjYtNDNhMC00YjIwLTg4YzQtMDdmZjNkZTU0MzRj", result.EncryptedKeys);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/vault/v1/keys/rekey");
            await this.httpMock.AssertRequestBodyContainsAsync("encrypted_keys", "test_encrypted_keys");
        }

        [Fact]
        public async Task TestListKvAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_object_summary.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/vault/v1/kv", HttpStatusCode.OK, fixture);
            var result = await this.service.ListKvAsync(new VaultListKvOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/vault/v1/kv");
        }

        [Fact]
        public async Task TestListKvAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/vault/v1/kv", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListKvAsync(new VaultListKvOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestCreateKvAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/object_metadata.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/vault/v1/kv", HttpStatusCode.OK, fixture);
            var options = new VaultCreateKvOptions();
            options.Name = "test_name";
            options.Value = "test_value";
            var result = await this.service.CreateKvAsync(options);
            Assert.NotNull(result);
            Assert.Equal("a1b2c3d4-e5f6-7890-abcd-ef1234567890", result.Id);
            Assert.Equal("environment_01K8ZYT4AWJ6XP0E0S8CTBHE3P", result.EnvironmentId);
            Assert.Equal("bf65e326-43a0-4b20-88c4-07ff3de5434c", result.KeyId);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/vault/v1/kv");
            await this.httpMock.AssertRequestBodyContainsAsync("name", "test_name");
            await this.httpMock.AssertRequestBodyContainsAsync("value", "test_value");
        }

        [Fact]
        public async Task TestGetNameAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/vault_object.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/vault/v1/kv/name/test_name", HttpStatusCode.OK, fixture);
            var result = await this.service.GetNameAsync("test_name");
            Assert.NotNull(result);
            Assert.Equal("a1b2c3d4-e5f6-7890-abcd-ef1234567890", result.Id);
            Assert.Equal("my-secret", result.Name);
            Assert.Equal("s3cr3t-v4lu3", result.Value);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/vault/v1/kv/name/test_name");
        }

        [Fact]
        public async Task TestGetKvAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/vault_object.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/vault/v1/kv/test_id", HttpStatusCode.OK, fixture);
            var result = await this.service.GetKvAsync("test_id");
            Assert.NotNull(result);
            Assert.Equal("a1b2c3d4-e5f6-7890-abcd-ef1234567890", result.Id);
            Assert.Equal("my-secret", result.Name);
            Assert.Equal("s3cr3t-v4lu3", result.Value);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/vault/v1/kv/test_id");
        }

        [Fact]
        public async Task TestUpdateKvAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/object_without_value.json");
            this.httpMock.MockResponse(HttpMethod.Put, "/vault/v1/kv/test_id", HttpStatusCode.OK, fixture);
            var options = new VaultUpdateKvOptions();
            options.Value = "test_value";
            var result = await this.service.UpdateKvAsync("test_id", options);
            Assert.NotNull(result);
            Assert.Equal("a1b2c3d4-e5f6-7890-abcd-ef1234567890", result.Id);
            Assert.Equal("my-secret", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Put, "/vault/v1/kv/test_id");
            await this.httpMock.AssertRequestBodyContainsAsync("value", "test_value");
        }

        [Fact]
        public async Task TestDeleteKvAsync()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/vault/v1/kv/test_id", HttpStatusCode.NoContent, "");
            await this.service.DeleteKvAsync("test_id", new VaultDeleteKvOptions());
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/vault/v1/kv/test_id");
        }

        [Fact]
        public async Task TestListKvMetadataAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/object_without_value.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/vault/v1/kv/test_id/metadata", HttpStatusCode.OK, fixture);
            var result = await this.service.ListKvMetadataAsync("test_id");
            Assert.NotNull(result);
            Assert.Equal("a1b2c3d4-e5f6-7890-abcd-ef1234567890", result.Id);
            Assert.Equal("my-secret", result.Name);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/vault/v1/kv/test_id/metadata");
        }

        [Fact]
        public async Task TestListKvVersionsAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/version_list_response.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/vault/v1/kv/test_id/versions", HttpStatusCode.OK, fixture);
            var result = await this.service.ListKvVersionsAsync("test_id");
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/vault/v1/kv/test_id/versions");
        }

        [Fact]
        public async Task TestListKvAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/object_summary.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/vault/v1/kv", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<ObjectSummary>();
            await foreach (var item in this.service.ListKvAutoPagingAsync(new VaultListKvOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListKvAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/vault/v1/kv", HttpStatusCode.OK, new[] { empty });

            var items = new List<ObjectSummary>();
            await foreach (var item in this.service.ListKvAutoPagingAsync(new VaultListKvOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.CreateDataKeyAsync(new VaultCreateDataKeyOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.CreateDataKeyAsync(new VaultCreateDataKeyOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.CreateDataKeyAsync(new VaultCreateDataKeyOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.CreateDataKeyAsync(new VaultCreateDataKeyOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.CreateDataKeyAsync(new VaultCreateDataKeyOptions()));
        }
    }
}
