// This file is auto-generated by oagen. Do not edit.

namespace WorkOSTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using WorkOS;
    using Xunit;

    public class WorkosServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly WorkosService service;

        public WorkosServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new WorkOSClient(new WorkOSOptions
            {
                ApiKey = "sk_test",
                ClientId = "client_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new WorkosService(client);
        }

        [Fact]
        public async Task TestCreateWebhook()
        {
            var fixture = System.IO.File.ReadAllText("testdata/work_os_webhooks_response.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/workos/webhooks", HttpStatusCode.OK, fixture);
            var options = new WorkosCreateWebhookOptions();
            options.Id = "test_id";
            options.Event = "test_event";
            var result = await this.service.CreateWebhook(options);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/workos/webhooks");
            await this.httpMock.AssertRequestBodyContainsAsync("id", "test_id");
            await this.httpMock.AssertRequestBodyContainsAsync("event", "test_event");
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationError>(() => this.service.CreateWebhook(new WorkosCreateWebhookOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundError>(() => this.service.CreateWebhook(new WorkosCreateWebhookOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityError>(() => this.service.CreateWebhook(new WorkosCreateWebhookOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededError>(() => this.service.CreateWebhook(new WorkosCreateWebhookOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerError>(() => this.service.CreateWebhook(new WorkosCreateWebhookOptions()));
        }
    }
}
