// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="FeatureFlagsService.List"/>: List Feature Flags</summary>
    public class FeatureFlagsListOptions : ListOptions
    {
    }

    /// <summary>Request options for <see cref="FeatureFlagsService.Disable"/>: Disable a feature flag</summary>
    public class FeatureFlagsDisableOptions : BaseOptions
    {
    }

    /// <summary>Request options for <see cref="FeatureFlagsService.Enable"/>: Enable a feature flag</summary>
    public class FeatureFlagsEnableOptions : BaseOptions
    {
    }

    /// <summary>Request options for <see cref="FeatureFlagsService.CreateTarget"/>: Create or update a feature flag target</summary>
    public class FeatureFlagsCreateTargetOptions : BaseOptions
    {
    }
}
