// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="WidgetsService.CreateToken"/>: Generate a Widget token.</summary>
    public class WidgetsCreateTokenOptions : BaseOptions
    {
        /// <summary>The identifier of the Organization to create the widget session for.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; } = default!;

        /// <summary>The identifier of the user to create the widget session for. Required when using the users:manage scope.</summary>
        [JsonProperty("user_id")]
        [STJS.JsonPropertyName("user_id")]
        public string? UserId { get; set; }

        /// <summary>The scopes to grant to the widget session. Determines which widgets the session can access.</summary>
        [JsonProperty("scopes")]
        [STJS.JsonPropertyName("scopes")]
        public List<WidgetSessionTokenScopes>? Scopes { get; set; }

    }
}
