// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the authkit magic auth API operations on <see cref="WorkOSClient"/>.</summary>
    public class AuthkitMagicAuthService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthkitMagicAuthService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public AuthkitMagicAuthService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthkitMagicAuthService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public AuthkitMagicAuthService(WorkOSClient client) : base(client) { }

        /// <summary>Create a Magic Auth code</summary>
        /// <remarks>
        /// Sends a one-time authentication code to the user's email address. The code expires in 10 minutes. To verify the code, authenticate the user with Magic Auth.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="MagicAuthSendMagicAuthCodeAndReturnResponse"/> result.</returns>
        public virtual async Task<MagicAuthSendMagicAuthCodeAndReturnResponse> CreateMagicAuth(AuthkitMagicAuthCreateMagicAuthOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<MagicAuthSendMagicAuthCodeAndReturnResponse>("/user_management/magic_auth", options, requestOptions, cancellationToken);
        }

        /// <summary>Magic Auth</summary>
        /// <remarks>
        /// Sends a one-time authentication code to the user’s email address. The code expires in 10 minutes. To verify the code, authenticate the user with Magic Auth.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task SendMagicAuth(AuthkitMagicAuthSendMagicAuthOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            await this.PostAsync<object>("/user_management/magic_auth/send", options, requestOptions, cancellationToken);
        }

        /// <summary>Get Magic Auth code details</summary>
        /// <remarks>
        /// Get the details of an existing Magic Auth code that can be used to authenticate a user.
        /// </remarks>
        /// <param name="id">The id.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="MagicAuthGetResponse"/> result.</returns>
        public virtual async Task<MagicAuthGetResponse> GetMagicAuth(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<MagicAuthGetResponse>($"/user_management/magic_auth/{id}", null, requestOptions, cancellationToken);
        }
    }
}
