// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="MultiFactorAuthService.VerifyChallengeAsync"/>: Verify Challenge</summary>
    public class MultiFactorAuthVerifyChallengeOptions : BaseOptions
    {
        /// <summary>The one-time code to verify.</summary>
        public string Code { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="MultiFactorAuthService.EnrollFactorAsync"/>: Enroll Factor</summary>
    public class MultiFactorAuthEnrollFactorOptions : BaseOptions
    {
        /// <summary>The type of factor to enroll.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public AuthenticationFactorsCreateRequestType Type { get; set; }

        /// <summary>Required when type is 'sms'.</summary>
        public string? PhoneNumber { get; set; }

        /// <summary>Required when type is 'totp'.</summary>
        public string? TotpIssuer { get; set; }

        /// <summary>Required when type is 'totp'.</summary>
        public string? TotpUser { get; set; }

        /// <summary>The ID of the user to associate the factor with.</summary>
        public string? UserId { get; set; }

    }

    /// <summary>Request options for <see cref="MultiFactorAuthService.ChallengeFactorAsync"/>: Challenge Factor</summary>
    public class MultiFactorAuthChallengeFactorOptions : BaseOptions
    {
        /// <summary>A custom template for the SMS message. Use the {{code}} placeholder to include the verification code.</summary>
        public string? SmsTemplate { get; set; }

    }

    /// <summary>Request options for <see cref="MultiFactorAuthService.ListUserAuthFactorsAsync"/>: List authentication factors</summary>
    public class MultiFactorAuthListUserAuthFactorsOptions : ListOptions
    {
    }

    /// <summary>Request options for <see cref="MultiFactorAuthService.CreateUserAuthFactorAsync"/>: Enroll an authentication factor</summary>
    public class MultiFactorAuthCreateUserAuthFactorOptions : BaseOptions
    {
        /// <summary>The type of the factor to enroll.</summary>
        public string Type { get; set; } = default!;

        /// <summary>Your application or company name displayed in the user's authenticator app.</summary>
        public string? TotpIssuer { get; set; }

        /// <summary>The user's account name displayed in their authenticator app.</summary>
        public string? TotpUser { get; set; }

        /// <summary>The Base32-encoded shared secret for TOTP factors. This can be provided when creating the auth factor, otherwise it will be generated. The algorithm used to derive TOTP codes is SHA-1, the code length is 6 digits, and the timestep is 30 seconds – the secret must be compatible with these parameters.</summary>
        public string? TotpSecret { get; set; }

    }
}
