// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="PlatformTeamsService.CreateTeamAsync"/>: Create a team</summary>
    public class PlatformTeamsCreateTeamOptions : BaseOptions
    {
        /// <summary>The email address of the person who will administer the team. An invitation is sent to this address.</summary>
        public string AdminEmail { get; set; } = default!;

        /// <summary>Name of the team.</summary>
        public string Name { get; set; } = default!;

    }
}
