// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the organizations API operations on <see cref="WorkOSClient"/>.</summary>
    public class OrganizationsService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationsService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="WorkOSConfiguration.WorkOSClient"/>.
        /// </summary>
        public OrganizationsService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationsService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public OrganizationsService(WorkOSClient client) : base(client) { }

        /// <summary>List Organizations</summary>
        /// <remarks>
        /// Get a list of all of your existing organizations matching the criteria specified.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="Organization"/> results.</returns>
        public virtual async Task<WorkOSList<Organization>> List(OrganizationsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<WorkOSList<Organization>>("/organizations", options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="List"/>. Yields individual items across all pages.</summary>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="Organization"/> items.</returns>
        public virtual IAsyncEnumerable<Organization> ListAutoPagingAsync(OrganizationsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAutoPagingAsync<Organization>("/organizations", options, requestOptions, cancellationToken);
        }

        /// <summary>Create an Organization</summary>
        /// <remarks>
        /// Creates a new organization in the current environment.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="Organization"/> result.</returns>
        public virtual async Task<Organization> Create(OrganizationsCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PostAsync<Organization>("/organizations", options, requestOptions, cancellationToken);
        }

        /// <summary>Get an Organization by External ID</summary>
        /// <remarks>
        /// Get the details of an existing organization by an [external identifier](https://workos.com/docs/authkit/metadata/external-identifiers).
        /// </remarks>
        /// <param name="externalId">The external ID of the Organization.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="Organization"/> result.</returns>
        public virtual async Task<Organization> GetByExternalId(string externalId, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<Organization>($"/organizations/external_id/{externalId}", null, requestOptions, cancellationToken);
        }

        /// <summary>Get an Organization</summary>
        /// <remarks>
        /// Get the details of an existing organization.
        /// </remarks>
        /// <param name="id">Unique identifier of the Organization.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="Organization"/> result.</returns>
        public virtual async Task<Organization> Get(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<Organization>($"/organizations/{id}", null, requestOptions, cancellationToken);
        }

        /// <summary>Update an Organization</summary>
        /// <remarks>
        /// Updates an organization in the current environment.
        /// </remarks>
        /// <param name="id">Unique identifier of the Organization.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="Organization"/> result.</returns>
        public virtual async Task<Organization> Update(string id, OrganizationsUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.PutAsync<Organization>($"/organizations/{id}", options, requestOptions, cancellationToken);
        }

        /// <summary>Delete an Organization</summary>
        /// <remarks>
        /// Permanently deletes an organization in the current environment. It cannot be undone.
        /// </remarks>
        /// <param name="id">Unique identifier of the Organization.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task Delete(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            await this.DeleteAsync($"/organizations/{id}", null, requestOptions, cancellationToken);
        }

        /// <summary>Get Audit Log Configuration</summary>
        /// <remarks>
        /// Get the unified view of audit log trail and stream configuration for an organization.
        /// </remarks>
        /// <param name="id">Unique identifier of the Organization.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="AuditLogConfiguration"/> result.</returns>
        public virtual async Task<AuditLogConfiguration> GetAuditLogConfiguration(string id, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return await this.GetAsync<AuditLogConfiguration>($"/organizations/{id}/audit_log_configuration", null, requestOptions, cancellationToken);
        }
    }
}
