// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="VaultService.CreateDataKeyAsync"/>: Create a data key</summary>
    public class VaultCreateDataKeyOptions : BaseOptions
    {
        /// <summary>Map of values used to determine the encryption key.</summary>
        public Dictionary<string, string> Context { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="VaultService.CreateDecryptAsync"/>: Decrypt a data key</summary>
    public class VaultCreateDecryptOptions : BaseOptions
    {
        /// <summary>Base64-encoded encrypted data key to decrypt.</summary>
        public string Keys { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="VaultService.CreateRekeyAsync"/>: Re-encrypt a data key</summary>
    public class VaultCreateRekeyOptions : BaseOptions
    {
        /// <summary>Map of values used to determine the new encryption key.</summary>
        public Dictionary<string, string> Context { get; set; } = default!;

        /// <summary>Base64-encoded encrypted data key blob to re-encrypt.</summary>
        public string EncryptedKeys { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="VaultService.ListKvAsync"/>: List objects</summary>
    public class VaultListKvOptions : ListOptions
    {
        /// <summary>Filter results by name or structured search JSON.</summary>
        public string? Search { get; set; }

        /// <summary>ISO 8601 timestamp to filter by last modified time.</summary>
        public DateTimeOffset? UpdatedAfter { get; set; }

    }

    /// <summary>Request options for <see cref="VaultService.CreateKvAsync"/>: Create an object</summary>
    public class VaultCreateKvOptions : BaseOptions
    {
        /// <summary>Map of values used to determine the encryption key.</summary>
        public Dictionary<string, string> KeyContext { get; set; } = default!;

        /// <summary>Unique name for the object.</summary>
        public string Name { get; set; } = default!;

        /// <summary>Plaintext data to encrypt and store.</summary>
        public string Value { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="VaultService.UpdateKvAsync"/>: Update an object</summary>
    public class VaultUpdateKvOptions : BaseOptions
    {
        /// <summary>New plaintext value.</summary>
        public string Value { get; set; } = default!;

        /// <summary>ID of the expected current version for optimistic locking.</summary>
        public string? VersionCheck { get; set; }

    }

    /// <summary>Request options for <see cref="VaultService.DeleteKvAsync"/>: Delete an object</summary>
    public class VaultDeleteKvOptions : BaseOptions
    {
        /// <summary>Expected current version for optimistic locking.</summary>
        public string? VersionCheck { get; set; }

    }
}
