// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents an access token agent registration credential issued data detail.</summary>
    public class AccessTokenAgentRegistrationCredentialIssuedDataDetail
    {

        /// <summary>The kind of credential issued.</summary>
        public string Kind { get; internal set; } = "access_token";

        /// <summary>The JWT ID of the issued access token.</summary>
        public string Jti { get; set; } = default!;

        /// <summary>The timestamp when the access token expires.</summary>
        public OneOf.OneOf<string, string?> ExpiresAt { get; set; } = default!;
    }
}
