// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an add role permission.</summary>
    public class AddRolePermission
    {

        /// <summary>The slug of the permission to add to the role.</summary>
        [JsonProperty("slug")]
        [STJS.JsonPropertyName("slug")]
        public string Slug { get; set; } = default!;
    }
}
