// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an agent instance session.</summary>
    public class AgentInstanceSession
    {

        /// <summary>Distinguishes the agent instance session object.</summary>
        public string Object { get; internal set; } = "agent_instance_session";

        /// <summary>Unique identifier of the agent instance session.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The agent instance the session belongs to.</summary>
        public string AgentInstanceId { get; set; } = default!;

        /// <summary>Derived from `revoked_at` and `expires_at` at read time; a revoked session stays `revoked` even after it expires.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public AgentInstanceSessionStatus Status { get; set; }

        /// <summary>Timestamp when the session expires.</summary>
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>Timestamp when the session was revoked; `null` if it has not been revoked.</summary>
        public DateTimeOffset? RevokedAt { get; set; }

        /// <summary>Timestamp when the session was created.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>Timestamp when the session was last updated.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
