// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>The agent identity associated with this registration.</summary>
    public class AgentRegistrationAgentIdentity
    {

        /// <summary>Unique identifier of the agent identity.</summary>
        public string Id { get; set; } = default!;

        /// <summary>Identifier of the AuthKit user the agent identity is bound to, or `null` when the agent is not associated with a user.</summary>
        public string? UserlandUserId { get; set; }

        /// <summary>The timestamp when the agent identity was created.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>The timestamp when the agent identity was last updated.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
