// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>The event payload.</summary>
    public class AgentBlueprintCreatedData
    {

        /// <summary>Distinguishes the agent blueprint object.</summary>
        public string Object { get; internal set; } = "agent_blueprint";

        /// <summary>Unique identifier of the agent blueprint.</summary>
        public string Id { get; set; } = default!;

        /// <summary>Human-readable name of the agent blueprint.</summary>
        public string Name { get; set; } = default!;

        /// <summary>Human-readable description of the agent blueprint.</summary>
        public string? Description { get; set; }

        /// <summary>Permission slugs forming the ceiling on what sessions minted from this blueprint may do.</summary>
        public List<string> Permissions { get; set; } = default!;

        /// <summary>Who may mint sessions from this blueprint.</summary>
        public AgentBlueprintCreatedDataInvocableBy InvocableBy { get; set; } = default!;

        /// <summary>Token and session lifetimes for sessions minted from this blueprint.</summary>
        public AgentBlueprintCreatedDataSessionSetting SessionSettings { get; set; } = default!;

        /// <summary>The timestamp when the agent blueprint was created.</summary>
        public string CreatedAt { get; set; } = default!;

        /// <summary>The timestamp when the agent blueprint was last updated.</summary>
        public string UpdatedAt { get; set; } = default!;
    }
}
