// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents an agent instance session created.</summary>
    public class AgentInstanceSessionCreated : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new AgentInstanceSessionCreatedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
