// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents an agent registration credential issued data detail.</summary>
    public class AgentRegistrationCredentialIssuedDataDetail
    {

        /// <summary>The kind of credential issued.</summary>
        public string Kind { get; internal set; } = "api_key";

        /// <summary>The ID of the issued API key.</summary>
        public string ApiKeyId { get; set; } = default!;
    }
}
