// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an agent instance.</summary>
    public class AgentInstance
    {

        /// <summary>Distinguishes the agent instance object.</summary>
        public string Object { get; internal set; } = "agent_instance";

        /// <summary>Unique identifier of the agent instance.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The blueprint this instance was minted from.</summary>
        public string AgentBlueprintId { get; set; } = default!;

        /// <summary>The organization the instance acts within.</summary>
        public string OrganizationId { get; set; } = default!;

        /// <summary>The organization membership of the delegating user; `null` for autonomous instances.</summary>
        public string? OrganizationMembershipId { get; set; }

        /// <summary>Whether the instance acts on behalf of a specific user (`delegated`) or as itself (`autonomous`).</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public AgentInstanceCreatedDataType Type { get; set; }

        /// <summary>Timestamp when the agent instance was created.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>Timestamp when the agent instance was last updated.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
