// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a api key validation response.</summary>
    public class ApiKeyValidationResponse : WorkOSEntity<ApiKeyValidationResponse>
    {
        [JsonProperty("api_key")]
        [STJS.JsonPropertyName("api_key")]
        public ApiKey ApiKey { get; set; }
    }
}
