// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>The owner of the API key.</summary>
    /// <remarks>Structurally identical to <see cref="ApiKeyCreatedDataOwner"/>.</remarks>
    public class ApiKeyRevokedDataOwner : ApiKeyCreatedDataOwner { }
}
