// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents an api key updated.</summary>
    public class ApiKeyUpdated : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new ApiKeyUpdatedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
