// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>The event payload.</summary>
    public class ApiKeyCreatedData
    {

        /// <summary>Distinguishes the API key object.</summary>
        public string Object { get; internal set; } = "api_key";

        /// <summary>Unique identifier of the API key.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The owner of the API key.</summary>
        public ApiKeyCreatedDataOwner Owner { get; set; } = default!;

        /// <summary>The name of the API key.</summary>
        public string Name { get; set; } = default!;

        /// <summary>The obfuscated value of the API key.</summary>
        public string ObfuscatedValue { get; set; } = default!;

        /// <summary>The timestamp when the API key was last used.</summary>
        public string? LastUsedAt { get; set; }

        /// <summary>The permissions granted to the API key.</summary>
        public List<string> Permissions { get; set; } = default!;

        /// <summary>The timestamp when the API key was created.</summary>
        public string CreatedAt { get; set; } = default!;

        /// <summary>The timestamp when the API key was last updated.</summary>
        public string UpdatedAt { get; set; } = default!;
    }
}
