// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an api keys validate api key owner.</summary>
    public class ApiKeysValidateApiKeyOwner
    {

        /// <summary>The type of the resource.</summary>
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public string Type { get; internal set; } = "organization";

        /// <summary>The ID of the organization that owns this API key.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;
    }
}
