// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;

    /// <summary>Represents an audit log schema json.</summary>
    public class AuditLogSchemaJson
    {

        /// <summary>Distinguishes the Audit Log Schema object.</summary>
        public string Object { get; internal set; } = "audit_log_schema";

        /// <summary>The version of the schema.</summary>
        public long Version { get; set; }

        /// <summary>The metadata schema for the actor.</summary>
        public AuditLogSchemaJsonActor? Actor { get; set; }

        /// <summary>The list of targets for the schema.</summary>
        public List<AuditLogSchemaJsonTarget> Targets { get; set; } = default!;

        /// <summary>Additional data associated with the event or entity.</summary>
        public Dictionary<string, object>? Metadata { get; set; }

        /// <summary>The timestamp when the Audit Log Schema was created.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Typed accessor for <see cref="Metadata"/>. Returns the value stored under
        /// <paramref name="key"/> coerced to <typeparamref name="T"/>, or the default
        /// value when the key is missing or the value is not convertible.
        /// </summary>
        /// <typeparam name="T">Expected value type.</typeparam>
        /// <param name="key">The key to look up.</param>
        public T? GetMetadataAttribute<T>(string key)
        {
            if (this.Metadata == null)
            {
                return default;
            }

            if (!this.Metadata.TryGetValue(key, out var value))
            {
                return default;
            }

            if (value is T typed)
            {
                return typed;
            }

            if (value is Newtonsoft.Json.Linq.JToken token)
            {
                return token.ToObject<T>();
            }

            if (value is System.Text.Json.JsonElement element)
            {
                return System.Text.Json.JsonSerializer.Deserialize<T>(element.GetRawText());
            }

            return default;
        }
    }
}
