// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The Audit Log Stream currently configured for the organization, if any.</summary>
    public class AuditLogConfigurationLogStream
    {

        /// <summary>Unique identifier of the Audit Log Stream.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>The type of the Audit Log Stream destination.</summary>
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public AuditLogConfigurationLogStreamType Type { get; set; }

        /// <summary>The current state of the Audit Log Stream.</summary>
        [JsonProperty("state")]
        [STJS.JsonPropertyName("state")]
        public AuditLogConfigurationLogStreamState State { get; set; }

        /// <summary>ISO-8601 timestamp of when the last event was successfully synced, or null if no events have been synced.</summary>
        [JsonProperty("last_synced_at")]
        [STJS.JsonPropertyName("last_synced_at")]
        public string? LastSyncedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }
    }
}
