// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>The metadata schema for the actor.</summary>
    /// <remarks>Structurally identical to <see cref="AuditLogSchemaActor"/>.</remarks>
    public class AuditLogSchemaJsonActor : AuditLogSchemaActor { }
}
