// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents an audit log event create response.</summary>
    public class AuditLogEventCreateResponse
    {

        /// <summary>Whether the Audit Log event was created successfully.</summary>
        public bool Success { get; set; }
    }
}
