// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an audit log events create response.</summary>
    public class AuditLogEventsCreateResponse
    {

        /// <summary>Whether the operation was successful.</summary>
        [JsonProperty("success")]
        [STJS.JsonPropertyName("success")]
        public bool Success { get; set; }
    }
}
