// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>AuditLogExportsExportsResponse is structurally identical to AuditLogExportsExportResponse.</summary>
    public class AuditLogExportsExportsResponse : AuditLogExportsExportResponse { }
}
