// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an audit log event actor.</summary>
    public class AuditLogEventActor
    {

        /// <summary>Actor identifier.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>Actor type.</summary>
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public string Type { get; set; } = default!;

        /// <summary>Optional actor name.</summary>
        [JsonProperty("name")]
        [STJS.JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>Additional data associated with the event or entity.</summary>
        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public Dictionary<string, AnyOf<string, double, bool>>? Metadata { get; set; }
    }
}
