// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The Audit Log Stream currently configured for the organization, if any.</summary>
    public class AuditLogConfigurationLogStream
    {

        /// <summary>Unique identifier of the Audit Log Stream.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The type of the Audit Log Stream destination.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public AuditLogConfigurationLogStreamType Type { get; set; }

        /// <summary>The current state of the Audit Log Stream.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public AuditLogConfigurationLogStreamState State { get; set; }

        /// <summary>ISO-8601 timestamp of when the last event was successfully synced, or null if no events have been synced.</summary>
        public string? LastSyncedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }
    }
}
