// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>Represents an audit log schema target.</summary>
    /// <remarks>Structurally identical to <see cref="AuditLogSchemaJsonTarget"/>.</remarks>
    public class AuditLogSchemaTarget : AuditLogSchemaJsonTarget { }
}
