// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>AuthorizationResourcesUpdateResponse is structurally identical to AuthorizationListResourcesForMembershipItem.</summary>
    public class AuthorizationResourcesUpdateResponse : AuthorizationListResourcesForMembershipItem { }
}
