// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>AuthenticationSSOTimedOutDataSSO is structurally identical to AuthenticationSSOFailedDataSSO.</summary>
    public class AuthenticationSSOTimedOutDataSSO : AuthenticationSSOFailedDataSSO { }
}
