// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>AuthorizationResourceTypesFindBySlugResponseParentType is structurally identical to AuthorizationResourceTypesChildType.</summary>
    public class AuthorizationResourceTypesFindBySlugResponseParentType : AuthorizationResourceTypesChildType { }
}
