// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents an authentication passkey failed.</summary>
    public class AuthenticationPasskeyFailed : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new AuthenticationPasskeyFailedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
