// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>The event payload.</summary>
    public class AuthenticationOAuthFailedData
    {
        public string Type { get; internal set; } = "oauth";
        public string Status { get; internal set; } = "failed";

        /// <summary>The IP address of the request.</summary>
        public string? IpAddress { get; set; }

        /// <summary>The user agent of the request.</summary>
        public string? UserAgent { get; set; }

        /// <summary>The ID of the user.</summary>
        public string? UserId { get; set; }

        /// <summary>The email address of the user.</summary>
        public string? Email { get; set; }

        /// <summary>Details about the authentication error.</summary>
        public AuthenticationOAuthFailedDataError Error { get; set; } = default!;
    }
}
