// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>SMS-based authentication factor details.</summary>
    public class AuthenticationFactorEnrolledSms
    {

        /// <summary>The user's phone number for SMS-based authentication.</summary>
        [JsonProperty("phone_number")]
        [STJS.JsonPropertyName("phone_number")]
        public string PhoneNumber { get; set; } = default!;
    }
}
