// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>AuthorizationOrganizationRolesListResponseData is structurally identical to AuthorizationOrganizationRolePermissionsAddPermissionResponse.</summary>
    public class AuthorizationOrganizationRolesListResponseData : AuthorizationOrganizationRolePermissionsAddPermissionResponse { }
}
