// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>TOTP-based authentication factor details. Includes enrollment secrets only available at creation time.</summary>
    public class AuthenticationFactorEnrolledTotp
    {

        /// <summary>Your application or company name displayed in the user's authenticator app. Defaults to your WorkOS team name.</summary>
        public string Issuer { get; set; } = default!;

        /// <summary>The user's account name displayed in their authenticator app. Defaults to the user's email.</summary>
        public string User { get; set; } = default!;

        /// <summary>TOTP secret that can be manually entered into some authenticator apps in place of scanning a QR code.</summary>
        public string Secret { get; set; } = default!;

        /// <summary>Base64 encoded image containing scannable QR code.</summary>
        public string QrCode { get; set; } = default!;

        /// <summary>The `otpauth` URI that is encoded by the provided `qr_code`.</summary>
        public string Uri { get; set; } = default!;
    }
}
