// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>TOTP-based authentication factor details. Includes enrollment secrets only available at creation time.</summary>
    public class AuthenticationFactorEnrolledTotp
    {

        /// <summary>Your application or company name displayed in the user's authenticator app. Defaults to your WorkOS team name.</summary>
        [JsonProperty("issuer")]
        [STJS.JsonPropertyName("issuer")]
        public string Issuer { get; set; } = default!;

        /// <summary>The user's account name displayed in their authenticator app. Defaults to the user's email.</summary>
        [JsonProperty("user")]
        [STJS.JsonPropertyName("user")]
        public string User { get; set; } = default!;

        /// <summary>TOTP secret that can be manually entered into some authenticator apps in place of scanning a QR code.</summary>
        [JsonProperty("secret")]
        [STJS.JsonPropertyName("secret")]
        public string Secret { get; set; } = default!;

        /// <summary>Base64 encoded image containing scannable QR code.</summary>
        [JsonProperty("qr_code")]
        [STJS.JsonPropertyName("qr_code")]
        public string QrCode { get; set; } = default!;

        /// <summary>The `otpauth` URI that is encoded by the provided `qr_code`.</summary>
        [JsonProperty("uri")]
        [STJS.JsonPropertyName("uri")]
        public string Uri { get; set; } = default!;
    }
}
