// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>The event payload.</summary>
    public class AuthenticationEmailVerificationSucceededData
    {
        public string Type { get; internal set; } = "email_verification";
        public string Status { get; internal set; } = "succeeded";

        /// <summary>The IP address of the request.</summary>
        public string? IpAddress { get; set; }

        /// <summary>The user agent of the request.</summary>
        public string? UserAgent { get; set; }

        /// <summary>The ID of the user.</summary>
        public string UserId { get; set; } = default!;

        /// <summary>The email address of the user.</summary>
        public string Email { get; set; } = default!;
    }
}
