// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an authorization check response.</summary>
    public class AuthorizationCheckResponse
    {

        /// <summary>Whether the subject is authorized to perform the action on the resource.</summary>
        [JsonProperty("authorized")]
        [STJS.JsonPropertyName("authorized")]
        public bool Authorized { get; set; }
    }
}
