// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>AuthorizationRolePermissionsAddPermissionResponse is structurally identical to AuthorizationOrganizationRolePermissionsAddPermissionResponse.</summary>
    public class AuthorizationRolePermissionsAddPermissionResponse : AuthorizationOrganizationRolePermissionsAddPermissionResponse { }
}
