// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Details about the authentication error.</summary>
    public class AuthenticationEmailVerificationFailedDataError : WorkOSEntity<AuthenticationEmailVerificationFailedDataError>
    {

        /// <summary>The error code.</summary>
        [JsonProperty("code")]
        [STJS.JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>A human-readable error message.</summary>
        [JsonProperty("message")]
        [STJS.JsonPropertyName("message")]
        public string Message { get; set; }
    }
}
