// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an authentication factors create request.</summary>
    public class AuthenticationFactorsCreateRequest
    {

        /// <summary>The type of factor to enroll.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public AuthenticationFactorsCreateRequestType Type { get; set; }

        /// <summary>Required when type is 'sms'.</summary>
        public string? PhoneNumber { get; set; }

        /// <summary>Required when type is 'totp'.</summary>
        public string? TotpIssuer { get; set; }

        /// <summary>Required when type is 'totp'.</summary>
        public string? TotpUser { get; set; }

        /// <summary>The ID of the user to associate the factor with.</summary>
        public string? UserId { get; set; }
    }
}
