// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents an authorization resource.</summary>
    public class AuthorizationResource
    {

        /// <summary>Distinguishes the Resource object.</summary>
        public string Object { get; internal set; } = "authorization_resource";

        /// <summary>A human-readable name for the Resource.</summary>
        public string Name { get; set; } = default!;

        /// <summary>An optional description of the Resource.</summary>
        public string? Description { get; set; }

        /// <summary>The ID of the organization that owns the resource.</summary>
        public string OrganizationId { get; set; } = default!;

        /// <summary>The ID of the parent resource, if this resource is nested.</summary>
        public string? ParentResourceId { get; set; }

        /// <summary>The unique ID of the Resource.</summary>
        public string Id { get; set; } = default!;

        /// <summary>An identifier you provide to reference the resource in your system.</summary>
        public string ExternalId { get; set; } = default!;

        /// <summary>The slug of the resource type this resource belongs to.</summary>
        public string ResourceTypeSlug { get; set; } = default!;

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
