// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>AuthorizationResourceTypesFindBySlugResponse is structurally identical to AuthorizationResourceTypesCreateResponse.</summary>
    public class AuthorizationResourceTypesFindBySlugResponse : AuthorizationResourceTypesCreateResponse { }
}
