// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a challenge authentication factor.</summary>
    public class ChallengeAuthenticationFactor
    {

        /// <summary>A custom template for the SMS message. Use the {{code}} placeholder to include the verification code.</summary>
        public string? SmsTemplate { get; set; }
    }
}
