// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>ConfirmEmailChange is structurally identical to AuthenticationChallengesVerifyRequest.</summary>
    public class ConfirmEmailChange : AuthenticationChallengesVerifyRequest { }
}
