// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>ConnectionDeactivatedData is structurally identical to ConnectionActivatedData.</summary>
    public class ConnectionDeactivatedData : ConnectionActivatedData { }
}
