// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>SAML-specific options for the connection.</summary>
    public class ConnectionFindResponseOption
    {

        /// <summary>The X.509 certificate used for signing SAML assertions, base64-encoded.</summary>
        [JsonProperty("signing_cert")]
        [STJS.JsonPropertyName("signing_cert")]
        public AnyOf<string, string?> SigningCert { get; set; } = default!;
    }
}
