// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a connection activated.</summary>
    public class ConnectionActivated : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new ConnectionActivatedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
