// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The event payload.</summary>
    public class ConnectionDeletedData
    {

        /// <summary>Distinguishes the connection object.</summary>
        public string Object { get; internal set; } = "connection";

        /// <summary>Unique identifier of the connection.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The current state of the connection.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public ConnectionActivatedDataState State { get; set; }

        /// <summary>The name of the connection.</summary>
        public string Name { get; set; } = default!;

        /// <summary>The type of the connection.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public ConnectionActivatedDataConnectionType ConnectionType { get; set; }

        /// <summary>The ID of the organization the connection belongs to.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
