// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;

    /// <summary>Represents a connect application.</summary>
    public class ConnectApplication
    {

        /// <summary>Distinguishes the connect application object.</summary>
        public string Object { get; internal set; } = "connect_application";

        /// <summary>The unique ID of the connect application.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The client ID of the connect application.</summary>
        public string ClientId { get; set; } = default!;

        /// <summary>A description of the connect application.</summary>
        public string? Description { get; set; }

        /// <summary>The name of the connect application.</summary>
        public string Name { get; set; } = default!;

        /// <summary>The scopes available for this application.</summary>
        public List<string> Scopes { get; set; } = default!;

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>The type of the application.</summary>
        public string ApplicationType { get; internal set; } = "m2m";

        /// <summary>The ID of the organization the application belongs to.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>The redirect URIs configured for this application.</summary>
        public List<ConnectApplicationRedirectUri>? RedirectUris { get; set; }

        /// <summary>Whether the application uses PKCE for authorization.</summary>
        public bool? UsesPkce { get; set; }

        /// <summary>Whether the application is a first-party application.</summary>
        public bool IsFirstParty { get; internal set; } = true;

        /// <summary>Whether the application was dynamically registered.</summary>
        public bool WasDynamicallyRegistered { get; internal set; } = false;
    }
}
