// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>Represents a connection domain.</summary>
    /// <remarks>Structurally identical to <see cref="ConnectionActivatedDataDomain"/>.</remarks>
    public class ConnectionDomain : ConnectionActivatedDataDomain { }
}
