// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The event payload.</summary>
    public class ConnectionDeactivatedData : WorkOSEntity<ConnectionDeactivatedData>
    {

        /// <summary>Distinguishes the connection object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; set; }

        /// <summary>Unique identifier of the connection.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>The current state of the connection.</summary>
        [JsonProperty("state")]
        [STJS.JsonPropertyName("state")]
        public ConnectionDeactivatedDataState State { get; set; }

        /// <summary>The name of the connection.</summary>
        [JsonProperty("name")]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>The type of the connection.</summary>
        [JsonProperty("connection_type")]
        [STJS.JsonPropertyName("connection_type")]
        public ConnectionDeactivatedDataConnectionType ConnectionType { get; set; }

        /// <summary>The ID of the organization the connection belongs to.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public string CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public string UpdatedAt { get; set; }

        /// <summary>The external key of the connection.</summary>
        [JsonProperty("external_key")]
        [STJS.JsonPropertyName("external_key")]
        public string ExternalKey { get; set; }

        /// <summary>Deprecated. Use state instead.</summary>
        [JsonProperty("status")]
        [STJS.JsonPropertyName("status")]
        public ConnectionDeactivatedDataStatus Status { get; set; }

        /// <summary>The domains associated with the connection.</summary>
        [JsonProperty("domains")]
        [STJS.JsonPropertyName("domains")]
        public List<ConnectionDeactivatedDataDomain> Domains { get; set; }
    }
}
