// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create organization domain.</summary>
    public class CreateOrganizationDomain : WorkOSEntity<CreateOrganizationDomain>
    {

        /// <summary>The domain to add to the organization.</summary>
        [JsonProperty("domain")]
        [STJS.JsonPropertyName("domain")]
        public string Domain { get; set; } = default!;

        /// <summary>The ID of the organization to add the domain to.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; } = default!;
    }
}
