// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents a create organization api key.</summary>
    public class CreateOrganizationApiKey
    {

        /// <summary>The name for the API key.</summary>
        public string Name { get; set; } = default!;

        /// <summary>The permission slugs to assign to the API key.</summary>
        public List<string>? Permissions { get; set; }
    }
}
