// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create organization domain.</summary>
    public class CreateOrganizationDomain
    {

        /// <summary>The domain to be added to the organization. This should be a domain owned by the organization, and not a common consumer domain like gmail.com.</summary>
        [JsonProperty("domain")]
        [STJS.JsonPropertyName("domain")]
        public string Domain { get; set; } = default!;

        /// <summary>The identifier of the Organization to add the domain to.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; } = default!;
    }
}
