// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a data integration custom provider.</summary>
    public class DataIntegrationCustomProvider
    {

        /// <summary>A descriptive name for the custom provider.</summary>
        public string Name { get; set; } = default!;

        /// <summary>The provider's OAuth authorization endpoint.</summary>
        public string? AuthorizationUrl { get; set; }

        /// <summary>The provider's OAuth token endpoint.</summary>
        public string? TokenUrl { get; set; }

        /// <summary>The endpoint used to refresh tokens, if different from the token endpoint.</summary>
        public string? RefreshTokenUrl { get; set; }

        /// <summary>Whether PKCE is used during the authorization code flow.</summary>
        public bool PkceEnabled { get; set; }

        /// <summary>The separator used to join requested scopes.</summary>
        public string RequestScopeSeparator { get; set; } = default!;

        /// <summary>Whether at least one scope must be selected when connecting an account.</summary>
        public bool ScopesRequired { get; set; }

        /// <summary>Whether a client secret is required for this provider.</summary>
        public bool ClientSecretRequired { get; set; }

        /// <summary>Additional static query parameters appended to the authorization request.</summary>
        public Dictionary<string, string> AdditionalAuthorizationParameters { get; set; } = default!;

        /// <summary>The Content-Type used when exchanging the token request.</summary>
        public string TokenBodyContentType { get; set; } = default!;

        /// <summary>How client credentials are sent when exchanging authorization codes and refreshing tokens.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public CustomProviderDefinitionAuthenticateVia AuthenticateVia { get; set; }
    }
}
