// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a data integrations get data integration authorize url request.</summary>
    public class DataIntegrationsGetDataIntegrationAuthorizeUrlRequest
    {

        /// <summary>The ID of the user to authorize.</summary>
        public string UserId { get; set; } = default!;

        /// <summary>An organization ID to scope the authorization to a specific organization.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>The URL to redirect the user to after authorization.</summary>
        public string? ReturnTo { get; set; }
    }
}
