// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a data integration access token response.</summary>
    public class DataIntegrationAccessTokenResponse
    {

        /// <summary>Indicates whether the access token is valid and ready for use, or if reauthorization is required.</summary>
        public bool? Active { get; set; }

        /// <summary>The [access token](https://workos.com/docs/reference/pipes/access-token) object, present when `active` is `true`.</summary>
        public DataIntegrationAccessTokenResponseAccessToken? AccessToken { get; set; }

        /// <summary>- `"not_installed"`: The user does not have the integration installed.</summary>
        /// <remarks>
        /// - `"needs_reauthorization"`: The user needs to reauthorize the integration.
        /// </remarks>
        public DataIntegrationAccessTokenResponseError? Error { get; set; }
    }
}
