// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a data integration.</summary>
    public class DataIntegration
    {

        /// <summary>Distinguishes the Data Integration object.</summary>
        public string Object { get; internal set; } = "data_integration";

        /// <summary>Unique identifier of the Data Integration.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The provider slug for this Data Integration.</summary>
        public string Slug { get; set; } = default!;

        /// <summary>The integration type derived from the provider.</summary>
        public string IntegrationType { get; set; } = default!;

        /// <summary>An optional description of the Data Integration.</summary>
        public string? Description { get; set; }

        /// <summary>Whether the Data Integration is enabled.</summary>
        public bool Enabled { get; set; }

        /// <summary>The state of the Data Integration.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public DataIntegrationState State { get; set; }

        /// <summary>The OAuth scopes configured for the Data Integration. `null` when the provider's configured scopes are used.</summary>
        public List<string>? Scopes { get; set; }

        /// <summary>The OAuth redirect URI to register with the provider when configuring the custom application. Empty for `api_key` and `client_credentials` integrations, which run no authorization redirect.</summary>
        public string RedirectUri { get; set; } = default!;

        /// <summary>How accounts authenticate with the provider for this Data Integration.</summary>
        public List<ConnectedAccountAuthMethod> AuthMethods { get; set; } = default!;

        /// <summary>The integration-level OAuth app credentials. `null` for `api_key` and `client_credentials` integrations, which hold no integration-level credentials (secrets are installed per-tenant).</summary>
        public DataIntegrationCredential? Credentials { get; set; }

        /// <summary>The tenant installation created when an API key was supplied at creation time; `null` otherwise. Not populated on list/get responses.</summary>
        public DataIntegrationInstallation? Installation { get; set; }

        /// <summary>Provider-specific config values set on the Data Integration (e.g. a Snowflake `account`), keyed by config field. Only fields the provider declares are accepted.</summary>
        public Dictionary<string, string> Config { get; set; } = default!;

        /// <summary>The OAuth definition when this is a custom provider; `null` for built-in providers.</summary>
        public DataIntegrationCustomProvider? CustomProvider { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
