// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents a data integrations list response.</summary>
    public class DataIntegrationsListResponse
    {

        /// <summary>Indicates this is a list response.</summary>
        public string Object { get; internal set; } = "list";

        /// <summary>A list of [providers](https://workos.com/docs/reference/pipes/provider), each including the legacy `connected_account` field and the additive `connected_accounts` collection.</summary>
        public List<DataIntegrationsListResponseData> Data { get; set; } = default!;
    }
}
