// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a data integrations list response data connected account.</summary>
    public class DataIntegrationsListResponseDataConnectedAccount
    {

        /// <summary>Distinguishes the connected account object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; internal set; } = "connected_account";

        /// <summary>The unique identifier of the connected account.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>The [User](https://workos.com/docs/reference/authkit/user) identifier associated with this connection.</summary>
        [JsonProperty("user_id")]
        [STJS.JsonPropertyName("user_id")]
        public string? UserId { get; set; }

        /// <summary>The [Organization](https://workos.com/docs/reference/organization) identifier associated with this connection, or `null` if not scoped to an organization.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string? OrganizationId { get; set; }

        /// <summary>The OAuth scopes granted for this connection.</summary>
        [JsonProperty("scopes")]
        [STJS.JsonPropertyName("scopes")]
        public List<string> Scopes { get; set; } = default!;

        /// <summary>The state of the connected account:</summary>
        /// <remarks>
        /// - `connected`: The connection is active and tokens are valid.
        /// - `needs_reauthorization`: The user needs to reauthorize the connection, typically because required scopes have changed.
        /// - `disconnected`: The connection has been disconnected.
        /// </remarks>
        [JsonProperty("state", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonPropertyName("state")]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public ConnectedAccountState State { get; set; }

        /// <summary>The timestamp when the connection was created.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public string CreatedAt { get; set; } = default!;

        /// <summary>The timestamp when the connection was last updated.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public string UpdatedAt { get; set; } = default!;

        /// <summary>Use `user_id` instead.</summary>
        [System.Obsolete("This field is deprecated Use `user_id` instead.")]
        [JsonProperty("userlandUserId")]
        [STJS.JsonPropertyName("userlandUserId")]
        public string? UserlandUserId { get; set; }
    }
}
