// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a data integration authorize url response.</summary>
    public class DataIntegrationAuthorizeUrlResponse : WorkOSEntity<DataIntegrationAuthorizeUrlResponse>
    {

        /// <summary>The OAuth authorization URL to redirect the user to.</summary>
        [JsonProperty("url")]
        [STJS.JsonPropertyName("url")]
        public string Url { get; set; }
    }
}
