// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents a data integration configuration response.</summary>
    public class DataIntegrationConfigurationResponse
    {

        /// <summary>Distinguishes the data integration configuration object.</summary>
        public string Object { get; internal set; } = "data_integration_configuration";

        /// <summary>The unique identifier of the data integration.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The [Organization](https://workos.com/docs/reference/organization) this configuration applies to.</summary>
        public string OrganizationId { get; set; } = default!;

        /// <summary>The slug identifier of the provider (e.g., `github`, `slack`, `notion`).</summary>
        public string Slug { get; set; } = default!;

        /// <summary>The display name of the data integration.</summary>
        public string Name { get; set; } = default!;

        /// <summary>Whether the integration is enabled for this organization. Reflects the organization override when one exists, otherwise the provider default.</summary>
        public bool Enabled { get; set; }

        /// <summary>The OAuth scopes in effect for this organization. Reflects the organization override when one is set, otherwise the provider scopes, or `null` when none are configured.</summary>
        public List<string>? Scopes { get; set; }

        /// <summary>The timestamp when the configuration was created.</summary>
        public string CreatedAt { get; set; } = default!;

        /// <summary>The timestamp when the configuration was last updated.</summary>
        public string UpdatedAt { get; set; } = default!;
        public DataIntegrationCredentials? Credentials { get; set; }
    }
}
