// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a data integrations get data integration authorize url request.</summary>
    public class DataIntegrationsGetDataIntegrationAuthorizeUrlRequest
    {

        /// <summary>The ID of the user to authorize.</summary>
        [JsonProperty("user_id")]
        [STJS.JsonPropertyName("user_id")]
        public string UserId { get; set; } = default!;

        /// <summary>An organization ID to scope the authorization to a specific organization.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string? OrganizationId { get; set; }

        /// <summary>The URL to redirect the user to after authorization.</summary>
        [JsonProperty("return_to")]
        [STJS.JsonPropertyName("return_to")]
        public string? ReturnTo { get; set; }
    }
}
