// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a directory users find response.</summary>
    public class DirectoryUsersFindResponse
    {

        /// <summary>The type of object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; internal set; } = "directory_user";

        /// <summary>The unique ID of the directory user.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>The identifier of the directory this user belongs to.</summary>
        [JsonProperty("directory_id")]
        [STJS.JsonPropertyName("directory_id")]
        public string DirectoryId { get; set; } = default!;

        /// <summary>The identifier of the Organization this user belongs to.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; } = default!;

        /// <summary>The user's identifier from the identity provider.</summary>
        [JsonProperty("idp_id")]
        [STJS.JsonPropertyName("idp_id")]
        public string IdpId { get; set; } = default!;

        /// <summary>The email address of the directory user.</summary>
        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string? Email { get; set; }

        /// <summary>The first name of the directory user.</summary>
        [JsonProperty("first_name")]
        [STJS.JsonPropertyName("first_name")]
        public string? FirstName { get; set; }

        /// <summary>The last name of the directory user.</summary>
        [JsonProperty("last_name")]
        [STJS.JsonPropertyName("last_name")]
        public string? LastName { get; set; }
        [JsonProperty("emails")]
        [STJS.JsonPropertyName("emails")]
        public List<DirectoryUsersFindResponseEmail>? Emails { get; set; }

        /// <summary>The job title of the directory user.</summary>
        [JsonProperty("job_title")]
        [STJS.JsonPropertyName("job_title")]
        public string? JobTitle { get; set; }

        /// <summary>The username of the directory user.</summary>
        [JsonProperty("username")]
        [STJS.JsonPropertyName("username")]
        public string? Username { get; set; }
        [JsonProperty("state", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonPropertyName("state")]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public DirectoryUsersFindResponseState State { get; set; }
        [JsonProperty("raw_attributes")]
        [STJS.JsonPropertyName("raw_attributes")]
        public Dictionary<string, object> RawAttributes { get; set; } = default!;
        [JsonProperty("custom_attributes")]
        [STJS.JsonPropertyName("custom_attributes")]
        public Dictionary<string, object> CustomAttributes { get; set; } = default!;
        [JsonProperty("role")]
        [STJS.JsonPropertyName("role")]
        public DirectoryUsersFindResponseRole? Role { get; set; }
        [JsonProperty("roles")]
        [STJS.JsonPropertyName("roles")]
        public List<DirectoryUsersFindResponseRole>? Roles { get; set; }

        /// <summary>The timestamp when the resource was created.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>The timestamp when the resource was last updated.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }
        [JsonProperty("groups")]
        [STJS.JsonPropertyName("groups")]
        public List<DirectoryUsersFindResponseGroup> Groups { get; set; } = default!;

        /// <summary>
        /// Typed accessor for <see cref="RawAttributes"/>. Returns the value stored under
        /// <paramref name="key"/> coerced to <typeparamref name="T"/>, or the default
        /// value when the key is missing or the value is not convertible.
        /// </summary>
        /// <typeparam name="T">Expected value type.</typeparam>
        /// <param name="key">The key to look up.</param>
        public T? GetRawAttributesAttribute<T>(string key)
        {
            if (this.RawAttributes == null) return default;
            if (!this.RawAttributes.TryGetValue(key, out var value)) return default;
            if (value is T typed) return typed;
            if (value is Newtonsoft.Json.Linq.JToken token) return token.ToObject<T>();
            if (value is System.Text.Json.JsonElement element)
            {
                return System.Text.Json.JsonSerializer.Deserialize<T>(element.GetRawText());
            }
            return default;
        }

        /// <summary>
        /// Typed accessor for <see cref="CustomAttributes"/>. Returns the value stored under
        /// <paramref name="key"/> coerced to <typeparamref name="T"/>, or the default
        /// value when the key is missing or the value is not convertible.
        /// </summary>
        /// <typeparam name="T">Expected value type.</typeparam>
        /// <param name="key">The key to look up.</param>
        public T? GetCustomAttributesAttribute<T>(string key)
        {
            if (this.CustomAttributes == null) return default;
            if (!this.CustomAttributes.TryGetValue(key, out var value)) return default;
            if (value is T typed) return typed;
            if (value is Newtonsoft.Json.Linq.JToken token) return token.ToObject<T>();
            if (value is System.Text.Json.JsonElement element)
            {
                return System.Text.Json.JsonSerializer.Deserialize<T>(element.GetRawText());
            }
            return default;
        }
    }
}
