// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a directory user email.</summary>
    public class DirectoryUserEmail
    {

        /// <summary>Whether this is the primary email address.</summary>
        public bool? Primary { get; set; }

        /// <summary>The type of email address.</summary>
        public string? Type { get; set; }

        /// <summary>The email address value.</summary>
        public string? Value { get; set; }
    }
}
