// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>DirectoryGroupsListItem is structurally identical to DirectoryGroupsFindResponse.</summary>
    public class DirectoryGroupsListItem : DirectoryGroupsFindResponse { }
}
