// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a directory.</summary>
    public class Directory : WorkOSEntity<Directory>
    {

        /// <summary>Distinguishes the Directory object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; set; }

        /// <summary>Unique identifier for the Directory.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>The unique identifier for the Organization in which the directory resides.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; }

        /// <summary>External Key for the Directory.</summary>
        [JsonProperty("external_key")]
        [STJS.JsonPropertyName("external_key")]
        public string ExternalKey { get; set; }

        /// <summary>The type of external Directory Provider integrated with.</summary>
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public DirectoryType Type { get; set; }

        /// <summary>Describes whether the Directory has been successfully connected to an external provider.</summary>
        [JsonProperty("state")]
        [STJS.JsonPropertyName("state")]
        public DirectoryState State { get; set; }

        /// <summary>The name of the directory.</summary>
        [JsonProperty("name")]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>The URL associated with an Enterprise Client.</summary>
        [JsonProperty("domain")]
        [STJS.JsonPropertyName("domain")]
        public string Domain { get; set; }

        /// <summary>Aggregate counts of directory users and groups synced from the provider.</summary>
        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public DirectoryMetadata Metadata { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public string CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public string UpdatedAt { get; set; }
    }
}
