// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>User counts for the directory.</summary>
    public class DirectoryFindResponseMetadataUser
    {

        /// <summary>The number of active users in the directory.</summary>
        [JsonProperty("active")]
        [STJS.JsonPropertyName("active")]
        public double Active { get; set; }

        /// <summary>The number of inactive users in the directory.</summary>
        [JsonProperty("inactive")]
        [STJS.JsonPropertyName("inactive")]
        public double Inactive { get; set; }
    }
}
