// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a directory user with groups.</summary>
    public class DirectoryUserWithGroups
    {

        /// <summary>Distinguishes the Directory User object.</summary>
        public string Object { get; internal set; } = "directory_user";

        /// <summary>Unique identifier for the Directory User.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The identifier of the Directory the Directory User belongs to.</summary>
        public string DirectoryId { get; set; } = default!;

        /// <summary>The identifier for the Organization in which the Directory resides.</summary>
        public string OrganizationId { get; set; } = default!;

        /// <summary>Unique identifier for the user, assigned by the Directory Provider. Different Directory Providers use different ID formats.</summary>
        public string IdpId { get; set; } = default!;

        /// <summary>The email address of the user.</summary>
        public string? Email { get; set; }

        /// <summary>The first name of the user.</summary>
        public string? FirstName { get; set; }

        /// <summary>The last name of the user.</summary>
        public string? LastName { get; set; }

        /// <summary>A list of email addresses for the user.</summary>
        [System.Obsolete("This field is deprecated.")]
        public List<DirectoryUserEmail>? Emails { get; set; }

        /// <summary>The job title of the user.</summary>
        [System.Obsolete("This field is deprecated.")]
        public string? JobTitle { get; set; }

        /// <summary>The username of the user.</summary>
        [System.Obsolete("This field is deprecated.")]
        public string? Username { get; set; }

        /// <summary>The state of the user.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public DirectoryUserState State { get; set; }

        /// <summary>The raw attributes received from the directory provider.</summary>
        [System.Obsolete("This field is deprecated.")]
        public Dictionary<string, object> RawAttributes { get; set; } = default!;

        /// <summary>An object containing the custom attribute mapping for the Directory Provider.</summary>
        public Dictionary<string, object> CustomAttributes { get; set; } = default!;
        public AddRolePermission? Role { get; set; }

        /// <summary>All roles assigned to the user.</summary>
        public List<AddRolePermission>? Roles { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>The directory groups the user belongs to. Use the List Directory Groups endpoint with a user filter instead.</summary>
        [System.Obsolete("This field is deprecated.")]
        public List<DirectoryGroup> Groups { get; set; } = default!;

        /// <summary>
        /// Typed accessor for <see cref="CustomAttributes"/>. Returns the value stored under
        /// <paramref name="key"/> coerced to <typeparamref name="T"/>, or the default
        /// value when the key is missing or the value is not convertible.
        /// </summary>
        /// <typeparam name="T">Expected value type.</typeparam>
        /// <param name="key">The key to look up.</param>
        public T? GetCustomAttributesAttribute<T>(string key)
        {
            if (this.CustomAttributes == null)
            {
                return default;
            }

            if (!this.CustomAttributes.TryGetValue(key, out var value))
            {
                return default;
            }

            if (value is T typed)
            {
                return typed;
            }

            if (value is Newtonsoft.Json.Linq.JToken token)
            {
                return token.ToObject<T>();
            }

            if (value is System.Text.Json.JsonElement element)
            {
                return System.Text.Json.JsonSerializer.Deserialize<T>(element.GetRawText());
            }

            return default;
        }
    }
}
