// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The event payload.</summary>
    public class DsyncDeletedData : WorkOSEntity<DsyncDeletedData>
    {

        /// <summary>Distinguishes the directory object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; set; }

        /// <summary>Unique identifier of the directory.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>The ID of the organization the directory belongs to.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; }

        /// <summary>The type of the directory.</summary>
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public DsyncDeletedDataType Type { get; set; }

        /// <summary>The current state of the directory.</summary>
        [JsonProperty("state")]
        [STJS.JsonPropertyName("state")]
        public DsyncDeletedDataState State { get; set; }

        /// <summary>The name of the directory.</summary>
        [JsonProperty("name")]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public string CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public string UpdatedAt { get; set; }
    }
}
