// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a dsync group updated.</summary>
    public class DsyncGroupUpdated : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new DsyncGroupUpdatedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
