// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a dsync activated data domain.</summary>
    public class DsyncActivatedDataDomain
    {

        /// <summary>Distinguishes the organization domain object.</summary>
        public string Object { get; internal set; } = "organization_domain";

        /// <summary>Unique identifier of the organization domain.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The domain value.</summary>
        public string Domain { get; set; } = default!;
    }
}
