// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an email verification.</summary>
    public class EmailVerification
    {

        /// <summary>Distinguishes the email verification object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; internal set; } = "email_verification";

        /// <summary>The unique ID of the email verification code.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>The unique ID of the user.</summary>
        [JsonProperty("user_id")]
        [STJS.JsonPropertyName("user_id")]
        public string UserId { get; set; } = default!;

        /// <summary>The email address of the user.</summary>
        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        /// <summary>The timestamp when the email verification code expires.</summary>
        [JsonProperty("expires_at")]
        [STJS.JsonPropertyName("expires_at")]
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>The code used to verify the email.</summary>
        [JsonProperty("code")]
        [STJS.JsonPropertyName("code")]
        public string Code { get; set; } = default!;
    }
}
