// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Pagination cursor for navigating to the next page of results.</summary>
    public class EventListListMetadata
    {

        /// <summary>An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.</summary>
        public string? After { get; set; }
    }
}
