// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents an event context google analytics session.</summary>
    public class EventContextGoogleAnalyticsSession
    {

        /// <summary>The Google Analytics container ID.</summary>
        public string ContainerId { get; set; } = default!;

        /// <summary>The Google Analytics session ID.</summary>
        public string? SessionId { get; set; }

        /// <summary>The Google Analytics session number.</summary>
        public string? SessionNumber { get; set; }
    }
}
