// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Additional context about the event.</summary>
    public class FlagRuleUpdatedContext
    {

        /// <summary>The client ID associated with the flag event.</summary>
        [JsonProperty("client_id")]
        [STJS.JsonPropertyName("client_id")]
        public string ClientId { get; set; } = default!;

        /// <summary>The actor who performed the action.</summary>
        [JsonProperty("actor")]
        [STJS.JsonPropertyName("actor")]
        public FlagRuleUpdatedContextActor Actor { get; set; } = default!;

        /// <summary>The access type of the flag rule.</summary>
        [JsonProperty("access_type", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonPropertyName("access_type")]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public FlagRuleUpdatedContextAccessType AccessType { get; set; }

        /// <summary>The configured targets for the flag rule.</summary>
        [JsonProperty("configured_targets")]
        [STJS.JsonPropertyName("configured_targets")]
        public FlagRuleUpdatedContextConfiguredTarget ConfiguredTargets { get; set; } = default!;

        /// <summary>Attributes that changed from their previous values.</summary>
        [JsonProperty("previous_attributes")]
        [STJS.JsonPropertyName("previous_attributes")]
        public FlagRuleUpdatedContextPreviousAttribute PreviousAttributes { get; set; } = default!;
    }
}
