// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;

    /// <summary>The event payload.</summary>
    public class FlagCreatedData
    {
        public string Object { get; internal set; } = "feature_flag";

        /// <summary>Unique identifier of the Feature Flag.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The ID of the environment the Feature Flag belongs to.</summary>
        public string EnvironmentId { get; set; } = default!;

        /// <summary>A unique key to reference the Feature Flag.</summary>
        public string Slug { get; set; } = default!;

        /// <summary>A descriptive name for the Feature Flag.</summary>
        public string Name { get; set; } = default!;

        /// <summary>A description for the Feature Flag.</summary>
        public string? Description { get; set; }

        /// <summary>The owner of the Feature Flag.</summary>
        public FeatureFlagOwner? Owner { get; set; }

        /// <summary>Labels assigned to the Feature Flag for categorizing and filtering.</summary>
        public List<string> Tags { get; set; } = default!;

        /// <summary>Specifies whether the Feature Flag is active for the current environment.</summary>
        public bool Enabled { get; set; }

        /// <summary>The value returned for users and organizations who don't match any configured targeting rules.</summary>
        public bool DefaultValue { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
