// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>Represents a flag rule updated context previous attribute context configured target user.</summary>
    /// <remarks>Structurally identical to <see cref="FlagRuleUpdatedContextConfiguredTargetUser"/>.</remarks>
    public class FlagRuleUpdatedContextPreviousAttributeContextConfiguredTargetUser : FlagRuleUpdatedContextConfiguredTargetUser { }
}
