// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a flag updated.</summary>
    public class FlagUpdated : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new FlagCreatedData Data { get; set; } = default!;

        /// <summary>Additional context about the event.</summary>
        public new FlagUpdatedContext Context { get; set; } = default!;
    }
}
