// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>FlagRuleUpdatedData is structurally identical to FlagCreatedData.</summary>
    public class FlagRuleUpdatedData : FlagCreatedData { }
}
