// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>The previous data attributes of the flag.</summary>
    public class FlagUpdatedContextPreviousAttributeData
    {

        /// <summary>The previous name of the flag.</summary>
        public string? Name { get; set; }

        /// <summary>The previous description of the flag.</summary>
        public string? Description { get; set; }

        /// <summary>The previous tags of the flag.</summary>
        public List<string>? Tags { get; set; }

        /// <summary>Whether the flag was previously enabled.</summary>
        public bool? Enabled { get; set; }

        /// <summary>The previous default value of the flag.</summary>
        public bool? DefaultValue { get; set; }
    }
}
