// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>Represents a flag created data owner.</summary>
    /// <remarks>Structurally identical to <see cref="FeatureFlagOwner"/>.</remarks>
    public class FlagCreatedDataOwner : FeatureFlagOwner { }
}
