// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Attributes that changed from their previous values.</summary>
    public class FlagUpdatedContextPreviousAttribute
    {

        /// <summary>The previous data attributes of the flag.</summary>
        [JsonProperty("data")]
        [STJS.JsonPropertyName("data")]
        public FlagUpdatedContextPreviousAttributeData? Data { get; set; }
    }
}
