// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a generate link.</summary>
    public class GenerateLink
    {

        /// <summary>The URL to go to when an admin clicks on your logo in the Admin Portal. If not specified, the return URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.</summary>
        [JsonProperty("return_url")]
        [STJS.JsonPropertyName("return_url")]
        public string? ReturnUrl { get; set; }

        /// <summary>The URL to redirect the admin to when they finish setup. If not specified, the success URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.</summary>
        [JsonProperty("success_url")]
        [STJS.JsonPropertyName("success_url")]
        public string? SuccessUrl { get; set; }

        /// <summary>An [Organization](https://workos.com/docs/reference/organization) identifier.</summary>
        [JsonProperty("organization")]
        [STJS.JsonPropertyName("organization")]
        public string Organization { get; set; } = default!;

        /// <summary>The intent of the Admin Portal.</summary>
        /// <remarks>
        /// - `sso` - Launch Admin Portal for creating SSO connections
        /// - `dsync` - Launch Admin Portal for creating Directory Sync connections
        /// - `audit_logs` - Launch Admin Portal for viewing Audit Logs
        /// - `log_streams` - Launch Admin Portal for creating Log Streams
        /// - `domain_verification` - Launch Admin Portal for Domain Verification
        /// - `certificate_renewal` - Launch Admin Portal for renewing SAML Certificates
        /// </remarks>
        [JsonProperty("intent")]
        [STJS.JsonPropertyName("intent")]
        public string Intent { get; set; } = default!;
        [JsonProperty("intent_options")]
        [STJS.JsonPropertyName("intent_options")]
        public IntentOptions? IntentOptions { get; set; }
    }
}
