// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents a group role assignment list.</summary>
    public class GroupRoleAssignmentList
    {

        /// <summary>Indicates this is a list response.</summary>
        public string Object { get; internal set; } = "list";

        /// <summary>The list of records for the current page.</summary>
        public List<GroupRoleAssignment> Data { get; set; } = default!;
        public ListMetadata ListMetadata { get; set; } = default!;
    }
}
