// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The event payload.</summary>
    public class InvitationAcceptedData
    {

        /// <summary>Distinguishes the invitation object.</summary>
        public string Object { get; internal set; } = "invitation";

        /// <summary>The unique ID of the invitation.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The email address of the recipient.</summary>
        public string Email { get; set; } = default!;

        /// <summary>The state of the invitation.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public InvitationAcceptedDataState State { get; set; }

        /// <summary>The timestamp when the invitation was accepted, or null if not yet accepted.</summary>
        public DateTimeOffset? AcceptedAt { get; set; }

        /// <summary>The timestamp when the invitation was revoked, or null if not revoked.</summary>
        public DateTimeOffset? RevokedAt { get; set; }

        /// <summary>The timestamp when the invitation expires.</summary>
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>The ID of the [organization](https://workos.com/docs/reference/organization) that the recipient will join.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>The ID of the user who invited the recipient, if provided.</summary>
        public string? InviterUserId { get; set; }

        /// <summary>The ID of the user who accepted the invitation, once accepted.</summary>
        public string? AcceptedUserId { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
