// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>InvitationResentData is structurally identical to InvitationAcceptedData.</summary>
    public class InvitationResentData : InvitationAcceptedData { }
}
