// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>InvitationCreatedData is structurally identical to InvitationAcceptedData.</summary>
    public class InvitationCreatedData : InvitationAcceptedData { }
}
