// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a invitation created.</summary>
    public class InvitationCreated : WorkOSEntity<InvitationCreated>
    {

        /// <summary>Unique identifier for the event.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; }
        [JsonProperty("event")]
        [STJS.JsonPropertyName("event")]
        public string Event { get; set; }

        /// <summary>The event payload.</summary>
        [JsonProperty("data")]
        [STJS.JsonPropertyName("data")]
        public InvitationCreatedData Data { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public string CreatedAt { get; set; }
        [JsonProperty("context")]
        [STJS.JsonPropertyName("context")]
        public EventContext Context { get; set; }

        /// <summary>Distinguishes the Event object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; set; }
    }
}
