// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a jwks response keys.</summary>
    public class JwksResponseKeys : WorkOSEntity<JwksResponseKeys>
    {

        /// <summary>Algorithm.</summary>
        [JsonProperty("alg")]
        [STJS.JsonPropertyName("alg")]
        public string Alg { get; set; }

        /// <summary>Key type.</summary>
        [JsonProperty("kty")]
        [STJS.JsonPropertyName("kty")]
        public string Kty { get; set; }

        /// <summary>Key use (signature).</summary>
        [JsonProperty("use")]
        [STJS.JsonPropertyName("use")]
        public string Use { get; set; }

        /// <summary>X.509 certificate chain.</summary>
        [JsonProperty("x5c")]
        [STJS.JsonPropertyName("x5c")]
        public List<string> X5C { get; set; }

        /// <summary>RSA modulus.</summary>
        [JsonProperty("n")]
        [STJS.JsonPropertyName("n")]
        public string N { get; set; }

        /// <summary>RSA exponent.</summary>
        [JsonProperty("e")]
        [STJS.JsonPropertyName("e")]
        public string E { get; set; }

        /// <summary>Key ID.</summary>
        [JsonProperty("kid")]
        [STJS.JsonPropertyName("kid")]
        public string Kid { get; set; }

        /// <summary>X.509 certificate SHA-256 thumbprint.</summary>
        [JsonProperty("x5t#S256")]
        [STJS.JsonPropertyName("x5t#S256")]
        public string X5TS256 { get; set; }
    }
}
