// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a JWT template response.</summary>
    public class JWTTemplateResponse
    {

        /// <summary>The object type.</summary>
        public string Object { get; internal set; } = "jwt_template";

        /// <summary>The JWT template content as a Liquid template string.</summary>
        public string Content { get; set; } = default!;

        /// <summary>The timestamp when the JWT template was created.</summary>
        public string CreatedAt { get; set; } = default!;

        /// <summary>The timestamp when the JWT template was last updated.</summary>
        public string UpdatedAt { get; set; } = default!;
    }
}
