// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a JWT templates update JWT template response.</summary>
    public class JWTTemplatesUpdateJWTTemplateResponse
    {

        /// <summary>The type of object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; internal set; } = "jwt_template";

        /// <summary>The content.</summary>
        [JsonProperty("content")]
        [STJS.JsonPropertyName("content")]
        public string Content { get; set; } = default!;

        /// <summary>The timestamp when the resource was created.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public string CreatedAt { get; set; } = default!;

        /// <summary>The timestamp when the resource was last updated.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public string UpdatedAt { get; set; } = default!;
    }
}
