// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;

    /// <summary>Metadata for a stored encrypted object.</summary>
    public class ObjectMetadata
    {

        /// <summary>Map of values used to determine the encryption key.</summary>
        public Dictionary<string, string> Context { get; set; } = default!;

        /// <summary>Environment the object belongs to.</summary>
        public string EnvironmentId { get; set; } = default!;

        /// <summary>Unique identifier of the object.</summary>
        public string Id { get; set; } = default!;

        /// <summary>Encryption key identifier.</summary>
        public string KeyId { get; set; } = default!;

        /// <summary>Timestamp of the last update.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
        public Actor UpdatedBy { get; set; } = default!;

        /// <summary>Current version identifier of the object.</summary>
        public string? VersionId { get; set; }
    }
}
