// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>OrganizationGetItem is structurally identical to OrganizationCreateItem.</summary>
    public class OrganizationGetItem : OrganizationCreateItem { }
}
