// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>The event payload.</summary>
    /// <remarks>Structurally identical to <see cref="OrganizationMembershipCreatedData"/>.</remarks>
    public class OrganizationMembershipUpdatedData : OrganizationMembershipCreatedData { }
}
