// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an organization create item.</summary>
    public class OrganizationCreateItem
    {

        /// <summary>The type of object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; internal set; } = "organization_domain";

        /// <summary>The unique ID of the organization domain.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>The identifier of the Organization this domain belongs to.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; } = default!;

        /// <summary>The domain name.</summary>
        [JsonProperty("domain")]
        [STJS.JsonPropertyName("domain")]
        public string Domain { get; set; } = default!;
        [JsonProperty("state")]
        [STJS.JsonPropertyName("state")]
        public OrganizationCreateItemState? State { get; set; }

        /// <summary>The prefix used for DNS verification.</summary>
        [JsonProperty("verification_prefix")]
        [STJS.JsonPropertyName("verification_prefix")]
        public string? VerificationPrefix { get; set; }

        /// <summary>The token used for domain verification.</summary>
        [JsonProperty("verification_token")]
        [STJS.JsonPropertyName("verification_token")]
        public string? VerificationToken { get; set; }
        [JsonProperty("verification_strategy")]
        [STJS.JsonPropertyName("verification_strategy")]
        public OrganizationCreateItemVerificationStrategy? VerificationStrategy { get; set; }

        /// <summary>The timestamp when the resource was created.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>The timestamp when the resource was last updated.</summary>
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
