// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The event payload.</summary>
    public class OrganizationDomainVerificationFailedData : WorkOSEntity<OrganizationDomainVerificationFailedData>
    {

        /// <summary>The reason the domain verification failed.</summary>
        [JsonProperty("reason")]
        [STJS.JsonPropertyName("reason")]
        public OrganizationDomainVerificationFailedDataReason Reason { get; set; }

        /// <summary>The organization domain that failed verification.</summary>
        [JsonProperty("organization_domain")]
        [STJS.JsonPropertyName("organization_domain")]
        public OrganizationDomainVerificationFailedDataOrganizationDomain OrganizationDomain { get; set; } = default!;
    }
}
