// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>OrganizationApiKeysOwner is structurally identical to ApiKeysValidateApiKeyOwner.</summary>
    public class OrganizationApiKeysOwner : ApiKeysValidateApiKeyOwner { }
}
