// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>OrganizationUpdatedData is structurally identical to OrganizationCreatedData.</summary>
    public class OrganizationUpdatedData : OrganizationCreatedData { }
}
