// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>OrganizationDomainVerificationFailedDataOrganizationDomain is structurally identical to OrganizationCreatedDataDomain.</summary>
    public class OrganizationDomainVerificationFailedDataOrganizationDomain : OrganizationCreatedDataDomain { }
}
