// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a organization input.</summary>
    public class OrganizationInput : WorkOSEntity<OrganizationInput>
    {

        /// <summary>The name of the organization.</summary>
        [JsonProperty("name")]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>Whether the organization allows profiles from outside the organization to sign in.</summary>
        [JsonProperty("allow_profiles_outside_organization")]
        [STJS.JsonPropertyName("allow_profiles_outside_organization")]
        public bool? AllowProfilesOutsideOrganization { get; set; }

        /// <summary>The domains associated with the organization. Deprecated in favor of `domain_data`.</summary>
        [JsonProperty("domains")]
        [STJS.JsonPropertyName("domains")]
        public List<string> Domains { get; set; }

        /// <summary>The domains associated with the organization, including verification state.</summary>
        [JsonProperty("domain_data")]
        [STJS.JsonPropertyName("domain_data")]
        public List<OrganizationDomainData> DomainData { get; set; }

        /// <summary>Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization.</summary>
        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>An external identifier for the Organization.</summary>
        [JsonProperty("external_id")]
        [STJS.JsonPropertyName("external_id")]
        public string ExternalId { get; set; }
    }
}
