// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;

    /// <summary>The event payload.</summary>
    public class OrganizationCreatedData
    {

        /// <summary>Distinguishes the Organization object.</summary>
        public string Object { get; internal set; } = "organization";

        /// <summary>Unique identifier of the Organization.</summary>
        public string Id { get; set; } = default!;

        /// <summary>A descriptive name for the Organization. This field does not need to be unique.</summary>
        public string Name { get; set; } = default!;

        /// <summary>List of Organization Domains.</summary>
        public List<OrganizationCreatedDataDomain> Domains { get; set; } = default!;

        /// <summary>Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization.</summary>
        public Dictionary<string, string> Metadata { get; set; } = default!;

        /// <summary>The external ID of the Organization.</summary>
        public string? ExternalId { get; set; }

        /// <summary>The Stripe customer ID of the Organization.</summary>
        public string? StripeCustomerId { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
