// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a password reset.</summary>
    public class PasswordReset
    {

        /// <summary>Distinguishes the password reset object.</summary>
        public string Object { get; internal set; } = "password_reset";

        /// <summary>The unique ID of the password reset object.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The unique ID of the user.</summary>
        public string UserId { get; set; } = default!;

        /// <summary>The email address of the user.</summary>
        public string Email { get; set; } = default!;

        /// <summary>The timestamp when the password reset token expires.</summary>
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>The timestamp when the password reset token was created.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>The token used to reset the password.</summary>
        public string PasswordResetToken { get; set; } = default!;

        /// <summary>The URL where the user can reset their password.</summary>
        public string PasswordResetUrl { get; set; } = default!;
    }
}
