// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The event payload.</summary>
    public class PasswordResetCreatedData : WorkOSEntity<PasswordResetCreatedData>
    {

        /// <summary>Distinguishes the password reset object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string Object { get; set; } = default!;

        /// <summary>The unique ID of the password reset object.</summary>
        [JsonProperty("id")]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>The unique ID of the user.</summary>
        [JsonProperty("user_id")]
        [STJS.JsonPropertyName("user_id")]
        public string UserId { get; set; } = default!;

        /// <summary>The email address of the user.</summary>
        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        /// <summary>The timestamp when the password reset token expires.</summary>
        [JsonProperty("expires_at")]
        [STJS.JsonPropertyName("expires_at")]
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>The timestamp when the password reset token was created.</summary>
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }
    }
}
