// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents a patch connection attribute maps.</summary>
    public class PatchConnectionAttributeMaps
    {

        /// <summary>How IdP attributes or claims map onto the standard WorkOS profile fields. Only the provided fields are updated.</summary>
        public CreateConnectionStandardAttributes? StandardAttributes { get; set; }

        /// <summary>How IdP attributes or claims map onto custom attributes, keyed by custom attribute name. Custom attributes must already be defined in the WorkOS dashboard. Only the provided keys are updated; a `null` value unsets that mapping.</summary>
        public Dictionary<string, string?>? CustomAttributes { get; set; }
    }
}
