// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a pipes account connection add failed.</summary>
    public class PipesAccountConnectionAddFailed : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new PipesAccountConnectionAddFailedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
