// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a pipes account connection connected.</summary>
    public class PipesAccountConnectionConnected : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new PipeConnectedAccount Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
