// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a radar standalone update radar list response.</summary>
    public class RadarStandaloneUpdateRadarListResponse
    {

        /// <summary>A human-readable message.</summary>
        [JsonProperty("message")]
        [STJS.JsonPropertyName("message")]
        public string? Message { get; set; }
    }
}
