// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a refresh token session authenticate request.</summary>
    public class RefreshTokenSessionAuthenticateRequest : WorkOSEntity<RefreshTokenSessionAuthenticateRequest>
    {

        /// <summary>The client ID of the application.</summary>
        [JsonProperty("client_id")]
        [STJS.JsonPropertyName("client_id")]
        public string ClientId { get; set; }

        /// <summary>The client secret of the application.</summary>
        [JsonProperty("client_secret")]
        [STJS.JsonPropertyName("client_secret")]
        public string ClientSecret { get; set; }
        [JsonProperty("grant_type")]
        [STJS.JsonPropertyName("grant_type")]
        public string GrantType { get; set; }

        /// <summary>The refresh token to exchange for new tokens.</summary>
        [JsonProperty("refresh_token")]
        [STJS.JsonPropertyName("refresh_token")]
        public string RefreshToken { get; set; }

        /// <summary>The ID of the organization to scope the session to.</summary>
        [JsonProperty("organization_id")]
        [STJS.JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; }

        /// <summary>The IP address of the user's request.</summary>
        [JsonProperty("ip_address")]
        [STJS.JsonPropertyName("ip_address")]
        public string IpAddress { get; set; }

        /// <summary>A unique identifier for the device.</summary>
        [JsonProperty("device_id")]
        [STJS.JsonPropertyName("device_id")]
        public string DeviceId { get; set; }

        /// <summary>The user agent string from the user's browser.</summary>
        [JsonProperty("user_agent")]
        [STJS.JsonPropertyName("user_agent")]
        public string UserAgent { get; set; }
    }
}
