// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a resend user invite options.</summary>
    public class ResendUserInviteOptions
    {

        /// <summary>The locale to use when rendering the invitation email. See [supported locales](https://workos.com/docs/authkit/hosted-ui/localization).</summary>
        public CreateUserInviteOptionsLocale? Locale { get; set; }
    }
}
