// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a revoke session.</summary>
    public class RevokeSession
    {

        /// <summary>The ID of the session to revoke. This can be extracted from the `sid` claim of the access token.</summary>
        public string SessionId { get; set; } = default!;

        /// <summary>The URL to redirect the user to after session revocation.</summary>
        public string? ReturnTo { get; set; }
    }
}
