// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents a role list.</summary>
    public class RoleList
    {
        public string Object { get; internal set; } = "list";

        /// <summary>The list of records for the current page.</summary>
        public List<Role> Data { get; set; } = default!;
    }
}
