// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a set role permissions.</summary>
    public class SetRolePermissions : WorkOSEntity<SetRolePermissions>
    {

        /// <summary>The permission slugs to assign to the role.</summary>
        [JsonProperty("permissions")]
        [STJS.JsonPropertyName("permissions")]
        public List<string> Permissions { get; set; } = default!;
    }
}
