// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a setting update app homepage url response.</summary>
    public class SettingUpdateAppHomepageUrlResponse
    {

        /// <summary>The type of object.</summary>
        [JsonProperty("object")]
        [STJS.JsonPropertyName("object")]
        public string? Object { get; set; }

        /// <summary>The app homepage URL.</summary>
        [JsonProperty("url")]
        [STJS.JsonPropertyName("url")]
        public string? Url { get; set; }
    }
}
