// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>The primary role assigned to the user.</summary>
    /// <remarks>Structurally identical to <see cref="AddRolePermission"/>.</remarks>
    public class SlimRole : AddRolePermission { }
}
