// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents an SSO logout authorize response.</summary>
    public class SSOLogoutAuthorizeResponse
    {

        /// <summary>The URL to redirect the user to in order to log out ([Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint ready to use).</summary>
        public string LogoutUrl { get; set; } = default!;

        /// <summary>The logout token to be used in the [Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint.</summary>
        public string LogoutToken { get; set; } = default!;
    }
}
