// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a sso logout authorize request.</summary>
    public class SSOLogoutAuthorizeRequest : WorkOSEntity<SSOLogoutAuthorizeRequest>
    {

        /// <summary>The unique ID of the profile to log out.</summary>
        [JsonProperty("profile_id")]
        [STJS.JsonPropertyName("profile_id")]
        public string ProfileId { get; set; }
    }
}
