// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a token query.</summary>
    public class TokenQuery
    {

        /// <summary>The client identifier for the application.</summary>
        [JsonProperty("client_id")]
        [STJS.JsonPropertyName("client_id")]
        public string ClientId { get; set; } = default!;

        /// <summary>The secret associated with the client. Used to authenticate the token request.</summary>
        [JsonProperty("client_secret")]
        [STJS.JsonPropertyName("client_secret")]
        public string ClientSecret { get; set; } = default!;

        /// <summary>The authorization code received from the authorization server.</summary>
        [JsonProperty("code")]
        [STJS.JsonPropertyName("code")]
        public string Code { get; set; } = default!;

        /// <summary>The grant type of the token request. Must be "authorization_code".</summary>
        [JsonProperty("grant_type")]
        [STJS.JsonPropertyName("grant_type")]
        public string GrantType { get; set; } = default!;
    }
}
