// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents an update organization.</summary>
    public class UpdateOrganization
    {

        /// <summary>The name of the organization.</summary>
        public string? Name { get; set; }

        /// <summary>Whether the organization allows profiles from outside the organization to sign in.</summary>
        public bool? AllowProfilesOutsideOrganization { get; set; }

        /// <summary>The domains associated with the organization. Deprecated in favor of `domain_data`.</summary>
        [System.Obsolete("This field is deprecated.")]
        public List<string>? Domains { get; set; }

        /// <summary>The domains associated with the organization, including verification state.</summary>
        public List<OrganizationDomainData>? DomainData { get; set; }

        /// <summary>The Stripe customer ID associated with the organization.</summary>
        public string? StripeCustomerId { get; set; }

        /// <summary>Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization.</summary>
        public Dictionary<string, string>? Metadata { get; set; }

        /// <summary>An external identifier for the Organization.</summary>
        public string? ExternalId { get; set; }
    }
}
