// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>UserOrganizationMembershipsCreateResponseRole is structurally identical to AddRolePermission.</summary>
    public class UserOrganizationMembershipsCreateResponseRole : AddRolePermission { }
}
