// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents an user consent option choice.</summary>
    public class UserConsentOptionChoice
    {

        /// <summary>The value of this choice.</summary>
        public string? Value { get; set; }

        /// <summary>A human-readable label for this choice.</summary>
        public string? Label { get; set; }
    }
}
