// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>UserGetEmailVerificationResponse is structurally identical to AuthorizationCodesCreateAuthenticateCodeResponse.</summary>
    public class UserGetEmailVerificationResponse : AuthorizationCodesCreateAuthenticateCodeResponse { }
}
