// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>Represents an user organization membership.</summary>
    /// <remarks>Structurally identical to <see cref="OrganizationMembership"/>.</remarks>
    public class UserOrganizationMembership : OrganizationMembership { }
}
