// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>UserFeatureFlagsListItem is structurally identical to FeatureFlagsDisableFlagResponse.</summary>
    public class UserFeatureFlagsListItem : FeatureFlagsDisableFlagResponse { }
}
