// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents an user deleted.</summary>
    public class UserDeleted
    {

        /// <summary>Unique identifier for the event.</summary>
        public string Id { get; set; } = default!;
        public string Event { get; internal set; } = "user.deleted";

        /// <summary>The event payload.</summary>
        public EmailChangeConfirmationUser Data { get; set; } = default!;

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }
        public EventContext? Context { get; set; }

        /// <summary>Distinguishes the Event object.</summary>
        public string Object { get; internal set; } = "event";
    }
}
