// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System.Collections.Generic;

    /// <summary>Represents an user object.</summary>
    public class UserObject
    {

        /// <summary>Your application's user identifier, which will be stored as an [`external_id`](https://workos.com/docs/authkit/metadata/external-identifiers). Used for upserting and deduplication.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The user's email address.</summary>
        public string Email { get; set; } = default!;

        /// <summary>The user's first name.</summary>
        public string? FirstName { get; set; }

        /// <summary>The user's last name.</summary>
        public string? LastName { get; set; }

        /// <summary>A set of key-value pairs to attach to the user.</summary>
        public Dictionary<string, string>? Metadata { get; set; }
    }
}
