// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents an user authentication factor enroll response.</summary>
    public class UserAuthenticationFactorEnrollResponse
    {

        /// <summary>The [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor) object that represents the additional authentication method used on top of the existing authentication strategy.</summary>
        public AuthenticationFactorEnrolled AuthenticationFactor { get; set; } = default!;

        /// <summary>The [authentication challenge](https://workos.com/docs/reference/authkit/mfa/authentication-challenge) object that is used to complete the authentication process.</summary>
        public AuthenticationChallenge AuthenticationChallenge { get; set; } = default!;
    }
}
