// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>UserOrganizationMembershipsUpdateResponse is structurally identical to UserOrganizationMembershipsCreateResponse.</summary>
    public class UserOrganizationMembershipsUpdateResponse : UserOrganizationMembershipsCreateResponse { }
}
