// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a vault data updated.</summary>
    public class VaultDataUpdated : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new VaultDataCreatedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
