// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;

    /// <summary>Represents a vault kek created.</summary>
    public class VaultKekCreated : EventSchema
    {

        /// <summary>The event payload.</summary>
        public new VaultKekCreatedData Data { get; set; } = default!;
        public new EventContext? Context { get; set; }
    }
}
