// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>The event payload.</summary>
    public class VaultByokKeyDeletedData
    {

        /// <summary>The unique identifier of the organization.</summary>
        public string OrganizationId { get; set; } = default!;

        /// <summary>The external key provider used for BYOK.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public VaultByokKeyDeletedDataKeyProvider KeyProvider { get; set; }
    }
}
