// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    /// <summary>Represents a verify email response.</summary>
    /// <remarks>Structurally identical to <see cref="ResetPasswordResponse"/>.</remarks>
    public class VerifyEmailResponse : ResetPasswordResponse { }
}
