// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a waitlist user.</summary>
    public class WaitlistUser
    {

        /// <summary>The unique ID of the waitlist entry.</summary>
        public string Id { get; set; } = default!;

        /// <summary>The email address of the user on the waitlist.</summary>
        public string Email { get; set; } = default!;

        /// <summary>The state of the waitlist entry.</summary>
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public UserManagementWaitlistsState State { get; set; }

        /// <summary>The timestamp when the entry was approved, or null if not yet approved.</summary>
        public DateTimeOffset? ApprovedAt { get; set; }

        /// <summary>Additional fields submitted when the user joined the waitlist. Values are user-provided — treat them as untrusted input when rendering or exporting.</summary>
        public Dictionary<string, string>? AdditionalFields { get; set; }

        /// <summary>The unique ID of the waitlist the entry belongs to.</summary>
        public string? WaitlistId { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>Distinguishes the Waitlist User object.</summary>
        public string Object { get; internal set; } = "waitlist_user";
    }
}
