// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{

    /// <summary>Represents a widget session token response.</summary>
    public class WidgetSessionTokenResponse
    {

        /// <summary>The widget session token.</summary>
        public string Token { get; set; } = default!;
    }
}
