// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="PipesService.UpdateDataIntegrationApiKeyAsync"/>: Upsert an API key for a connected account</summary>
    public class PipesUpdateDataIntegrationApiKeyOptions : BaseOptions
    {
        /// <summary>A [User](https://workos.com/docs/reference/authkit/user) identifier.</summary>
        public string UserId { get; set; } = default!;

        /// <summary>An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>The API key secret to store for this integration.</summary>
        public string Secret { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="PipesService.AuthorizeDataIntegrationAsync"/>: Get authorization URL</summary>
    public class PipesAuthorizeDataIntegrationOptions : BaseOptions
    {
        /// <summary>The ID of the user to authorize.</summary>
        public string UserId { get; set; } = default!;

        /// <summary>An organization ID to scope the authorization to a specific organization.</summary>
        public string? OrganizationId { get; set; }

        /// <summary>The URL to redirect the user to after authorization.</summary>
        public string? ReturnTo { get; set; }

    }

    /// <summary>Request options for <see cref="PipesService.CreateDataIntegrationCredentialAsync"/>: Vend credentials for a connected account</summary>
    public class PipesCreateDataIntegrationCredentialOptions : BaseOptions
    {
        /// <summary>A [User](https://workos.com/docs/reference/authkit/user) identifier.</summary>
        public string UserId { get; set; } = default!;

        /// <summary>An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.</summary>
        public string? OrganizationId { get; set; }

    }

    /// <summary>Request options for <see cref="PipesService.GetAccessTokenAsync"/>: Get an access token for a connected account</summary>
    public class PipesGetAccessTokenOptions : BaseOptions
    {
        /// <summary>A [User](https://workos.com/docs/reference/authkit/user) identifier.</summary>
        public string UserId { get; set; } = default!;

        /// <summary>An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.</summary>
        public string? OrganizationId { get; set; }

    }

    /// <summary>Request options for <see cref="PipesService.GetUserConnectedAccountAsync"/>: Get a connected account</summary>
    public class PipesGetUserConnectedAccountOptions : BaseOptions
    {
        /// <summary>An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.</summary>
        public string? OrganizationId { get; set; }

    }

    /// <summary>Request options for <see cref="PipesService.DeleteUserConnectedAccountAsync"/>: Delete a connected account</summary>
    public class PipesDeleteUserConnectedAccountOptions : BaseOptions
    {
        /// <summary>An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.</summary>
        public string? OrganizationId { get; set; }

    }

    /// <summary>Request options for <see cref="PipesService.ListUserDataProvidersAsync"/>: List providers for a user</summary>
    public class PipesListUserDataProvidersOptions : BaseOptions
    {
        /// <summary>An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to filter connections for a specific organization.</summary>
        public string? OrganizationId { get; set; }

    }
}
