name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test C# ${{ matrix.dotnet }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '6.x', '7.x', '8.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            ${{ matrix.dotnet }}
      - name: Test
        run: |
          dotnet build -c Debug src/WorkOS.net/WorkOS.net.csproj
          dotnet build -c Debug test/WorkOSTests/WorkOSTests.csproj
          dotnet test -c Debug -f netcoreapp3.1 test/WorkOSTests/WorkOSTests.csproj
