name: CI

on:
  push:
    branches:
      - "main"
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test C# ${{ matrix.dotnet }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: ["6.x", "7.x", "8.x"]
    steps:
      # TODO: Remove libssl1.1 installation once we drop support for .NET Core 3.1
      - name: Install libssl1.1 for .NET Core 3.1
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
          sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb
      - uses: actions/checkout@v4
      - name: Setup dotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            ${{ matrix.dotnet }}
      - name: Test
        run: |
          dotnet build -c Debug src/WorkOS.net/WorkOS.net.csproj
          dotnet build -c Debug test/WorkOSTests/WorkOSTests.csproj
          dotnet test -c Debug -f netcoreapp3.1 test/WorkOSTests/WorkOSTests.csproj
