name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup DotNet
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet pack -c Release src/WorkOS.net/WorkOS.net.csproj

      - name: NuGet login (trusted publishing)
        id: login
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.1.0
        with:
          user: workos

      - name: Publish
        run: dotnet nuget push src/WorkOS.net/bin/Release/WorkOS.net.*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
