// This file is auto-generated by oagen. Do not edit.

namespace WorkOS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="ApiKeysService.CreateValidation"/>: Validate API key</summary>
    public class ApiKeysCreateValidationOptions : BaseOptions
    {
        /// <summary>The value for an API key</summary>
        [JsonProperty("value")]
        [STJS.JsonPropertyName("value")]
        public string Value { get; set; } = default!;

    }
}
